### ISSUE TITLE
failed to find libmagic

### ISSUE THREAD

**Issue by amirhossein-razavi** [saleor/saleor#10004]
### What I'm trying to achieve
run project in local 

### Steps to reproduce the problem

1.
2.

### What I expected to happen
run project in local 

### Screenshots and logs

**System information**

Saleor version:
- 3

Operating system:
- [ ] Windows

This the output error when I run the python manage.py check command
But I already have libmagic install by running pip install libmagic

C:\Users\Amir\Desktop\saleor\saleor\settings.py:177: UserWarning: SECRET_KEY not configured, using a random temporary key.
  warnings.warn("SECRET_KEY not configured, using a random temporary key.")
Traceback (most recent call last):
  File "C:\Users\Amir\Desktop\saleor\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Amir\Desktop\saleor\saleor-venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\Amir\Desktop\saleor\saleor-venv\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\Amir\Desktop\saleor\saleor-venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Amir\Desktop\saleor\saleor-venv\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Amir\Desktop\saleor\saleor-venv\lib\site-packages\django\apps\config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Amir\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Amir\Desktop\saleor\saleor\plugins\models.py", line 6, in <module>
    from ..core.utils.json_serializer import CustomJsonEncoder
  File "C:\Users\Amir\Desktop\saleor\saleor\core\utils\__init__.py", line 15, in <module>
    from versatileimagefield.image_warmer import VersatileImageFieldWarmer
  File "C:\Users\Amir\Desktop\saleor\saleor-venv\lib\site-packages\versatileimagefield\image_warmer.py", line 8, in <module>
    from .utils import (
  File "C:\Users\Amir\Desktop\saleor\saleor-venv\lib\site-packages\versatileimagefield\utils.py", line 5, in <module>
    import magic
  File "C:\Users\Amir\Desktop\saleor\saleor-venv\lib\site-packages\magic\__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "C:\Users\Amir\Desktop\saleor\saleor-venv\lib\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by CossackDex** [comment]
Hi @amirhossein-razavi according to comments under [this issue](https://github.com/Yelp/elastalert/issues/1927#issuecomment-689927231) libmagic has a more complex installation process for windows. You can check mentioned comment for a guide on how to install it.

**Comment by trust0212** [comment]
I had same issue.
I used Python 3.9.7, and installed VS Build tools (for python).
Then it worked.

**Comment by Ritika1007** [comment]
I was also facing the same issue while running migrations, commented out python-magic==0.4.27  from requirements.txt and then installed the requirements, it worked fine.
python-magic-bin==0.4.14 ; python_version >= "3.9" and python_version < "3.10" and sys_platform == "win32"
# python-magic==0.4.27 ; python_version >= "3.9" and python_version < "3.10"

**Comment by Jarmos-san** [comment]
Devs from the future, if you stumbled across this thread through a quick Google Search and the [aforementioned solution](https://github.com/saleor/saleor/issues/10004#issuecomment-1732390396) didn't work for you, here's what you need to know.

Assuming you are on the same up-to-date version of Saleor (I'm on v3.18 as of leaving this comment), you will not find a `requirement.txt` file in the source code. There's a `pyproject.toml` file with the `python-magic` and `python-magic-bin` dependencies. The latter is meant to be installed on Windows. Do not mess around with these, let them be but ensure you update the `Dockerfile` and install [`libmagic1`](https://packages.debian.org/bookworm/libmagic1). The Python library `python-magic` depends on `libmagic1` without which your Docker build will probably fail!

I don't think it would be much of an issue when running Saleor on Windows natively (but I cannot verify this claim right now). On a containerised environment you will have to ensure all the necessary build tools are present before the Python libraries can run properly.
