### ISSUE TITLE
ImportError: Failed to import plugin saleor.plugins.webhook.plugin.WebhookPlugin: No module named 'pytest'

### ISSUE THREAD

**Issue by amityweb** [saleor/saleor#10333]
### What I'm trying to achieve
Upgrading my Saleor core to 3.6 via a forked (and unchanged) GitHub repo I have onto Heroku

### Steps to reproduce the problem
1. I go to my Heroku Deploy dashboard for the app
2. I enter 3.6 in the Deploy a GitHub Branch and hit Deploy

At the end I get an issue installing pytest:

```
Traceback (most recent call last):
  File "/app/saleor/plugins/apps.py", line 24, in load_and_check_plugin
    plugin = import_string(plugin_path)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/saleor/plugins/webhook/plugin.py", line 43, in <module>
    from .shipping import get_excluded_shipping_data, parse_list_shipping_methods_response
  File "/app/saleor/plugins/webhook/shipping.py", line 18, in <module>
    from .tasks import trigger_webhook_sync
  File "/app/saleor/plugins/webhook/tasks.py", line 29, in <module>
    from ...webhook import observability
  File "/app/saleor/webhook/observability/__init__.py", line 3, in <module>
    from .payloads import dump_payload
  File "/app/saleor/webhook/observability/payloads.py", line 16, in <module>
    from .obfuscation import (
  File "/app/saleor/webhook/observability/obfuscation.py", line 23, in <module>
    from ...graphql.api import schema
  File "/app/saleor/graphql/api.py", line 9, in <module>
    from .checkout.schema import CheckoutMutations, CheckoutQueries
  File "/app/saleor/graphql/checkout/schema.py", line 13, in <module>
    from ..payment.mutations import CheckoutPaymentCreate
  File "/app/saleor/graphql/payment/mutations.py", line 38, in <module>
    from ..checkout.mutations.utils import get_checkout
  File "/app/saleor/graphql/checkout/mutations/__init__.py", line 3, in <module>
    from .checkout_complete import CheckoutComplete
  File "/app/saleor/graphql/checkout/mutations/checkout_complete.py", line 28, in <module>
    from ...order.types import Order
  File "/app/saleor/graphql/order/types.py", line 30, in <module>
    from ...order import OrderStatus, calculations, models
  File "/app/saleor/order/calculations.py", line 11, in <module>
    from ..order.tests.test_calculations import TaxData
  File "/app/saleor/order/tests/test_calculations.py", line 5, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/app/.heroku/python/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/app/saleor/plugins/apps.py", line 20, in ready
    self.load_and_check_plugin(plugin_path)
  File "/app/saleor/plugins/apps.py", line 26, in load_and_check_plugin
    raise (ImportError(f"Failed to import plugin {plugin_path}: {e}"))
ImportError: Failed to import plugin saleor.plugins.webhook.plugin.WebhookPlugin: No module named 'pytest'
```

### What I expected to happen
Version is deployed OK

**System information**
Saleor version:
3.6

Operating system:
- [ ] MacOS

**Comment by korycins** [comment]
Hey @amityweb, 
Thanks for raising this. It looks like there is an incorrect import added by mistake. If you need a temporary solution, you could install `requirments_dev.txt` instead of `requirments.txt`. I will prepare a fix in the meantime.

**Comment by amityweb** [comment]
I’m so glad you replied I need to send to customer later. If there’s info online about the requirements file I’ll take a look but that’s new to me hope I can find how to do it! Thanks.
