### ISSUE TITLE
Bug: Unable to start, smart_text error

### ISSUE THREAD

**Issue by blackyzero** [saleor/saleor#10556]
### What are you trying to achieve?

Start core api

### Steps to reproduce the problem

- Install all dependencies
- Start core api

### What did you expect to happen?

Core started

### Logs

```
2022-09-06 00:42:57,373 INFO django.utils.autoreload Watching for file changes with StatReloader [PID:26309:MainThread]
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/services/saleor/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/opt/services/saleor/venv/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/opt/services/saleor/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/opt/services/saleor/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/opt/services/saleor/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/opt/services/saleor/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/services/saleor/venv/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/services/saleor/venv/lib/python3.9/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/saleor/core/saleor/product/models.py", line 34, in <module>
    from django.utils.encoding import smart_text
ImportError: cannot import name 'smart_text' from 'django.utils.encoding' (/opt/services/saleor/venv/lib/python3.9/site-packages/django/utils/encoding.py)

```

### Environment

Saleor version: 3.7.2
OS and version: Debian 11, node 14.20.0

**Comment by blackyzero** [comment]
found, it's cause of Django version 4.

**Comment by patrys** [comment]
Django 4.0 is only supported by the `main` branch. It will become part of the next minor release (3.8).

**Comment by blackyzero** [comment]
Great. Thanks for this info.
