### ISSUE TITLE
Bug: psycopg2.errors.UndefinedFunction: function gen_random_uuid() does not exist

### ISSUE THREAD

**Issue by roperi** [saleor/saleor#10678]
### What are you trying to achieve?

Apply database migrations when installing Saleor core.

### Steps to reproduce the problem

1. `python manage.py migrate`
2.  Fails with `psycopg2.errors.UndefinedFunction: function gen_random_uuid() does not exist`

### What did you expect to happen?

I expected to see all database migrations applied successfully so I can continue with the Saleor installation. 

### Logs

```
python manage.py migrate
2022-09-16 15:01:25,742 WARNING saleor.core.jwt_manager RSA_PRIVATE_KEY is missing. Using temporary key for local development with DEBUG mode. [PID:28039:MainThread]
2022-09-16 15:01:25,867 WARNING py.warnings /home/admin/workspace/mysite/backend/saleor/saleor/urls.py:60: UserWarning: The debug toolbar was not installed. Ignore the error.             settings.py should already have warned the user about it.
  warnings.warn(
 [PID:28039:MainThread]
Operations to perform:
  Apply all migrations: account, app, attribute, auth, channel, checkout, contenttypes, core, csv, discount, django_celery_beat, django_prices_openexchangerates, django_prices_vatlayer, giftcard, invoice, menu, order, page, payment, plugins, product, schedulers, shipping, site, sites, thumbnail, warehouse, webhook
Running migrations:
  Applying account.0068_user_uuid...Traceback (most recent call last):
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedFunction: function gen_random_uuid() does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 105, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 130, in _run_sql
    schema_editor.execute(statement, params=None)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/admin/.virtualenvs/mysite/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: function gen_random_uuid() does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

### Environment

Saleor version: 3.7
OS and version: Debian 10

**Comment by satvikt** [comment]
This also happens when we run test cases against a new database - in this case, the test database created with respect to the current saleor database in use doesn't have `gen_random_uuid` by default.

As of now, the problem can be solved by entering into the database and manually executing 

`CREATE EXTENSION pgcrypto;`

as also mentioned at [link](https://github.com/saleor/saleor/issues/10648#issuecomment-1249507171)
