### ISSUE TITLE
Bug: [transactionCreate] HANDLE_PAYMENTS permissions

### ISSUE THREAD

**Issue by benjamin-carriou** [saleor/saleor#11075]
### What are you trying to achieve?

I'am trying to create a transaction based on a existant checkout with the `transactionCreate` mutation

### Steps to reproduce the problem

1. Execute `transactionCreate` mutation:

```bash
mutation {
  transactionCreate(
    id: "Q2hlY2tvdXQ6MTcyMzUyOTEtNWY1My00MjUyLThjYWEtNWFmMjlhZjExMjhl"
    transaction: {
      status: "Authorized"
      type: "Credit card"
      reference: "PSP-ref123"
      availableActions: [VOID, CHARGE]
      amountAuthorized: { currency: "EUR", amount: 3200 }
    }
    transactionEvent: {
      status: SUCCESS
      name: "Authorized credit card"
      reference: "PSP-ref123"
    }
  ) {
    transaction {
      id
    }
  }
}
```

2. Return the following error:

```bash
{
  "errors": [
    {
      "message": "You need one of the following permissions: HANDLE_PAYMENTS",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "transactionCreate"
      ],
      "extensions": {
        "exception": {
          "code": "PermissionDenied",
          "stacktrace": [
            "Traceback (most recent call last):",
            "  File \"/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py\", line 452, in resolve_or_error",
            "    return executor.execute(resolve_fn, source, info, **args)",
            "  File \"/usr/local/lib/python3.9/site-packages/graphql/execution/executors/sync.py\", line 16, in execute",
            "    return fn(*args, **kwargs)",
            "  File \"/app/saleor/graphql/core/mutations.py\", line 369, in mutate",
            "    raise PermissionDenied(permissions=cls._meta.permissions)",
            "saleor.core.exceptions.PermissionDenied: You need one of the following permissions: HANDLE_PAYMENTS"
          ]
        }
      }
    }
  ],
  "data": {
    "transactionCreate": null
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 0,
      "maximumAvailable": 50000
    }
  }
}
```

### What did you expect to happen?

I expect to happen to create a transaction but it return me a problem of missing permission (`HANDLE_PAYMENTS`) with my account.

But, i use the admin account and when I query my permissions groups for my current account,
 I get the following response where the `HANDLE_PAYMENTS` permission is configured:

```bash
query {me {id permissionGroups{id name} userPermissions{name code}}}

{
  "data": {
    "me": {
      "id": "VXNlcjoy",
      "permissionGroups": [
        {
          "id": "R3JvdXA6MQ==",
          "name": "Full Access"
        },
        {
          "id": "R3JvdXA6MjQ=",
          "name": "admin"
        }
      ],
      "userPermissions": [
        {
          "name": "Handle checkouts",
          "code": "HANDLE_CHECKOUTS"
        },
        {
          "name": "Handle payments",
          "code": "HANDLE_PAYMENTS"
        },
        {
          "name": "Handle taxes",
          "code": "HANDLE_TAXES"
        },
        {
          "name": "Impersonate user.",
          "code": "IMPERSONATE_USER"
        },
        {
          "name": "Manage apps",
          "code": "MANAGE_APPS"
        },
        {
          "name": "Manage channels.",
          "code": "MANAGE_CHANNELS"
        },
        {
          "name": "Manage checkouts",
          "code": "MANAGE_CHECKOUTS"
        },
        {
          "name": "Manage sales and vouchers.",
          "code": "MANAGE_DISCOUNTS"
        },
        {
          "name": "Manage gift cards.",
          "code": "MANAGE_GIFT_CARD"
        },
        {
          "name": "Manage navigation.",
          "code": "MANAGE_MENUS"
        },
        {
          "name": "Manage observability",
          "code": "MANAGE_OBSERVABILITY"
        },
        {
          "name": "Manage orders.",
          "code": "MANAGE_ORDERS"
        },
        {
          "name": "Manage page types and attributes.",
          "code": "MANAGE_PAGE_TYPES_AND_ATTRIBUTES"
        },
        {
          "name": "Manage pages.",
          "code": "MANAGE_PAGES"
        },
        {
          "name": "Manage plugins",
          "code": "MANAGE_PLUGINS"
        },
        {
          "name": "Manage product types and attributes.",
          "code": "MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES"
        },
        {
          "name": "Manage products.",
          "code": "MANAGE_PRODUCTS"
        },
        {
          "name": "Manage settings.",
          "code": "MANAGE_SETTINGS"
        },
        {
          "name": "Manage shipping.",
          "code": "MANAGE_SHIPPING"
        },
        {
          "name": "Manage staff.",
          "code": "MANAGE_STAFF"
        },
        {
          "name": "Manage translations.",
          "code": "MANAGE_TRANSLATIONS"
        },
        {
          "name": "Manage customers.",
          "code": "MANAGE_USERS"
        }
      ]
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 3,
      "maximumAvailable": 50000
    }
  }
}

```

I'am trying from the playground and I set in HTTP HEADERS the following content:

```bash
{
  "Authorization": "JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.[...]"
}
```

This configuration works for another mutations (ex: `productCreate`,  `checkoutCreate`, `checkoutPaymentCreate`, ...)

### Logs

```bash
022-10-28 07:40:36,042 INFO saleor.graphql.errors.handled A query had an error [PID:23:Thread-629]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.9/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/app/saleor/graphql/core/mutations.py", line 369, in mutate
    raise PermissionDenied(permissions=cls._meta.permissions)
saleor.core.exceptions.PermissionDenied: You need one of the following permissions: HANDLE_PAYMENTS
```

### Environment

- Saleor version:

```bash
saleor-platform_react-storefront   latest       21e057cdd830   10 days ago   2.58GB
saleor-platform_api                latest       0b1ec0729d7a   10 days ago   986MB
saleor-platform_worker             latest       0b1ec0729d7a   10 days ago   986MB
saleor-platform_dashboard          latest       cc7a3c06dfc5   10 days ago   2.41GB
infra_worker                       latest       073853b46839   12 days ago   986MB
infra_api                          latest       073853b46839   12 days ago   986MB
```
- OS and version: dockerized environment

```bash
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.3
 Git commit:        20.10.12-0ubuntu4
 Built:             Mon Mar  7 17:10:06 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.3
  Git commit:       20.10.12-0ubuntu4
  Built:            Mon Mar  7 15:57:50 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu3
  GitCommit:        
 runc:
  Version:          1.1.0-0ubuntu1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

```bash
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by benjamin-carriou** [comment]
Hi,

Any news about this ?

Thx

**Comment by benjamin-carriou** [comment]
Hi,

Any news about this ?

Thx

**Comment by benjamin-carriou** [comment]
Anybody to help ?

**Comment by benjamin-carriou** [comment]
Any news ?!? :(

**Comment by szczecha** [comment]
Hi, at the time of creating the issue, it was only possible to create a transaction as an app with HANDLE_PAYMENTS permissions

```
Create transaction for checkout or order. Requires the following permissions: AUTHENTICATED_APP and HANDLE_PAYMENTS.
```
Since version 3.13, staff can also create transactions if they have HANDLE_PAYMENTS permission

**Comment by nataalii** [comment]
have you resolved the issue?
