### ISSUE TITLE
Bug: window10 install failed with OSError: cannot load library 'C:\Program Files\GTK3-Runtime Win64\bin\pango-1.0-0.dll': error 0x7f

### ISSUE THREAD

**Issue by loveJasmine** [saleor/saleor#11085]
### What are you trying to achieve?

(saleor-venv) PS C:\saleor> python manage.py migrate
C:\saleor\saleor\settings.py:191: UserWarning: SECRET_KEY not configured, using a random temporary key.
  warnings.warn("SECRET_KEY not configured, using a random temporary key.")

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----

Traceback (most recent call last):
  File "C:\saleor\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
...

OSError: cannot load library 'C:\Program Files\GTK3-Runtime Win64\bin\pango-1.0-0.dll': error 0x7f

### Steps to reproduce the problem

NA

### What did you expect to happen?

sucess

### Logs

(saleor-venv) PS C:\saleor> python manage.py migrate
C:\saleor\saleor\settings.py:191: UserWarning: SECRET_KEY not configured, using a random temporary key.
  warnings.warn("SECRET_KEY not configured, using a random temporary key.")

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----

Traceback (most recent call last):
  File "C:\saleor\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\saleor\saleor-venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\saleor\saleor-venv\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\saleor\saleor-venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\saleor\saleor-venv\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "C:\saleor\saleor\plugins\apps.py", line 20, in ready
    self.load_and_check_plugin(plugin_path)
  File "C:\saleor\saleor\plugins\apps.py", line 24, in load_and_check_plugin
    plugin = import_string(plugin_path)
  File "C:\saleor\saleor-venv\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "C:\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\saleor\saleor\plugins\invoicing\plugin.py", line 11, in <module>
    from .utils import generate_invoice_number, generate_invoice_pdf
  File "C:\saleor\saleor\plugins\invoicing\utils.py", line 10, in <module>
    from weasyprint import HTML
  File "C:\saleor\saleor-venv\lib\site-packages\weasyprint\__init__.py", line 336, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\saleor\saleor-venv\lib\site-packages\weasyprint\css\__init__.py", line 25, in <module>
    from . import computed_values, counters, media_queries
  File "C:\saleor\saleor-venv\lib\site-packages\weasyprint\css\computed_values.py", line 11, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "C:\saleor\saleor-venv\lib\site-packages\weasyprint\text\ffi.py", line 421, in <module>
    pango = _dlopen(
  File "C:\saleor\saleor-venv\lib\site-packages\weasyprint\text\ffi.py", line 407, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "C:\saleor\saleor-venv\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\saleor\saleor-venv\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\saleor\saleor-venv\lib\site-packages\cffi\api.py", line 828, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library 'C:\Program Files\GTK3-Runtime Win64\bin\pango-1.0-0.dll': error 0x7f

### Environment

Saleor version: …
OS and version: …
window 10
python 3.9
latest salor

**Comment by peelar** [comment]
Hello @loveJasmine 👋 

One of our developers investigated it and to him, it looks like an issue with `weasyprint` not being able to find the necessary libraries. It appears to be common on Windows, deserving even [a separate chapter](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#missing-library) in their docs.

The problem emerges in the Saleor invoicing plugin. I understand you use it, yes?

**Comment by loveJasmine** [comment]
no, so maybe I just ignore it or skip it

**Comment by peelar** [comment]
@loveJasmine let's check that, yes.

**Comment by maarcingebala** [comment]
Closing due to no activity, please reopen if there is still something to help here with.
