### ISSUE TITLE
Bug: Error while running Saleor

### ISSUE THREAD

**Issue by vitalii-bulyzhyn** [saleor/saleor#11722]
### What are you trying to achieve?

I'm new to Saleor and wanted to play around with it. I tried to start it with docker compose as this [doc](https://docs.saleor.io/docs/3.x/setup/docker-compose) suggests, but got a problem with installing of one of the packages in the container (see log below)

### Steps to reproduce the problem

```
git clone https://github.com/saleor/saleor-platform.git --recursive --jobs 3
cd saleor-platform
docker-compose build
```

### What did you expect to happen?

Not to crah while building

### Logs

```
#0 41.58 Collecting measurement==3.2.0
#0 41.60   Downloading measurement-3.2.0.tar.gz (12 kB)
#0 41.62   Preparing metadata (setup.py): started
#0 49.09   Preparing metadata (setup.py): finished with status 'error'
#0 49.09   error: subprocess-exited-with-error
#0 49.09   
#0 49.09   × python setup.py egg_info did not run successfully.
#0 49.09   │ exit code: 1
#0 49.09   ╰─> [14 lines of output]
#0 49.09       Traceback (most recent call last):
#0 49.09         File "<string>", line 2, in <module>
#0 49.09         File "<pip-setuptools-caller>", line 34, in <module>
#0 49.09         File "/tmp/pip-install-eb10n8vo/measurement_332b29e47ef244cabbfb8458e2b59739/setup.py", line 4, in <module>
#0 49.09           setup(use_scm_version=True)
#0 49.09         File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
#0 49.09           _install_setup_requires(attrs)
#0 49.09         File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
#0 49.09           dist.fetch_build_eggs(dist.setup_requires)
#0 49.09         File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
#0 49.09           resolved_dists = pkg_resources.working_set.resolve(
#0 49.09         File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
#0 49.09           raise VersionConflict(dist, req).with_context(dependent_req)
#0 49.09       pkg_resources.ContextualVersionConflict: (sphinxcontrib.applehelp 1.0.3 (/tmp/pip-install-eb10n8vo/measurement_332b29e47ef244cabbfb8458e2b59739/.eggs/sphinxcontrib.applehelp-1.0.3-py3.9.egg), Requirement.parse('sphinxcontrib-applehelp'), {'sphinx'})
#0 49.09       [end of output]
#0 49.09   
#0 49.09   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 49.09 error: metadata-generation-failed
#0 49.09 
#0 49.09 × Encountered error while generating package metadata.
#0 49.09 ╰─> See above for output.
#0 49.09 
#0 49.09 note: This is an issue with the package mentioned above, not pip.
#0 49.09 hint: See above for details.
#0 49.11 WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
#0 49.11 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
failed to solve: process "/bin/sh -c pip install -r requirements_dev.txt" did not complete successfully: exit code: 1
```

### Environment

Saleor version: latest
OS and version: macOS Monterey Version 12.0
Chip: Apple M1 Pro

**Comment by vitalii-bulyzhyn** [comment]
Same happens when I tried to deploy to Heroku, so might be related to the **measurement** package itself?

**Comment by akhial** [comment]
Getting same bug on versions `3.9.12` and `3.10.0`, version `3.8.9` builds fine.

**Comment by vitalii-bulyzhyn** [comment]
@akhial I updated it to the latest release and was able t run it without problems

**Comment by akhial** [comment]
Yes it's building fine now, very puzzling... Thanks!
