### ISSUE TITLE
django.contrib.auth.models.Permission doesn't declare an explicit app_label

### ISSUE THREAD

**Issue by malibres-indra** [saleor/saleor#12060]
### What are you trying to achieve?

I installed saleor in my ubuntu environment using docker base on this page but when I run command for creating superuser `docker-compose run --rm api python3 manage.py createsuperuser` I got a error saying that ` RuntimeError: Model class django.contrib.auth.models.Permission doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`. I attch a gif photo for the live issue.

![saleor](https://user-images.githubusercontent.com/91582576/219900609-238e9ff1-8914-42d7-9ec1-1ad14e351dc3.gif)

![image](https://user-images.githubusercontent.com/91582576/219900632-6c869bac-6511-4e05-9ffc-c8915ca154f0.png)

### Steps to reproduce the problem

1) Run a command
2) Create superuser

### What did you expect to happen?

Creating super user so that I can sin in as admin

### Logs

Creating saleor-platform_api_run ... done
2023-02-18 21:38:34,238 WARNING saleor.core.jwt_manager RSA_PRIVATE_KEY is missing. Using temporary key for local development with DEBUG mode. [PID:1:MainThread]
Traceback (most recent call last):
  File "/app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 100, in handle
    default_username = get_default_username(database=database)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/management/__init__.py", line 115, in get_default_username
    from django.contrib.auth import models as auth_app
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/models.py", line 35, in <module>
    class Permission(models.Model):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 113, in __new__
    raise RuntimeError(
RuntimeError: Model class django.contrib.auth.models.Permission doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
ERROR: 1

### Environment

Ubuntu 20.04

**Comment by malibres-indra** [comment]
Looks like it is already fix in #11810 but does not reflect in the @https://github.com/saleor/saleor-platform.git, I already fix by merging the files from @https://github.com/saleor/saleor/pull/11810/commits/7de650c4f6b33ba4baa260bc560ee73ae2186440
to my local files.

**Comment by fowczarek** [comment]
I fix this problem in [3.10.3](https://github.com/saleor/saleor/releases/tag/3.10.3). 
Actual `Saleor-Platform` fetches Saleor-Core 3.10.1 instead of the newest version of Core. 
I prepare a version bump in `Saleor-Platform`. 

Another workaround is to switch Saleor-Core to the newest release for:
- [3.10.10](https://github.com/saleor/saleor/releases/tag/3.10.10) 
- [3.11.8](https://github.com/saleor/saleor/releases/tag/3.11.8)

The newest releases are always available [here](https://github.com/saleor/saleor/releases).
