### ISSUE TITLE
Bug: S3 File Upload returns "sequence item 0: expected str instance, NoneType found"

### ISSUE THREAD

**Issue by drazenbebic** [saleor/saleor#12418]
### What are you trying to achieve?

I'm trying to set up S3 to work with my local instance of Saleor. I followed this guide: https://docs.saleor.io/docs/3.x/setup/media-s3

I tried configuring it, but I cannot upload an image after creating a product. It's worth noting that the bucket doesn't have a public-read ACL, instead I'm serving the images via CloudFront. When I manually add the files to my S3 bucket - it works; the images are shown in the Dashboard. This means that the environment variables are passed. The problem is only with the media upload, every file upload absolutely failed.

Any help would be greatly appreciated!

### Steps to reproduce the problem

1. Cloned the `saleor/saleor-platform`
2. Edited the `backend.env` file
3. Ran the migrations
4. Created an admin account
5. Ran `docker compose up --force-recreate -d`
6. Logged into the Dashboard at `localhost:9000`
7. Created a new product
8. Uploaded an image to the new product
9. Received the following error message `sequence item 0: expected str instance, NoneType found`

### What did you expect to happen?

I expected the selected image to be uploaded to my S3 Bucket. 

### Logs

Logs from Docker container (saleor-platform-api):

```
2023-03-27 15:43:13 [2023-03-27 13:43:13 +0000] [26] [INFO] Booting worker with pid: 26
2023-03-27 15:43:13 [2023-03-27 13:43:13 +0000] [26] [INFO] Started server process [26]
2023-03-27 15:43:13 [2023-03-27 13:43:13 +0000] [27] [INFO] Booting worker with pid: 27
2023-03-27 15:43:13 [2023-03-27 13:43:13 +0000] [27] [INFO] Started server process [27]
2023-03-27 15:44:12 2023-03-27 13:44:12,730 ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:26:ThreadPoolExecutor-0_0]
2023-03-27 15:44:12 Traceback (most recent call last):
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
2023-03-27 15:44:12     return executor.execute(resolve_fn, source, info, **args)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/graphql/execution/executors/sync.py", line 16, in execute
2023-03-27 15:44:12     return fn(*args, **kwargs)
2023-03-27 15:44:12   File "/app/saleor/graphql/core/mutations.py", line 517, in mutate
2023-03-27 15:44:12     response = cls.perform_mutation(root, info, **data)
2023-03-27 15:44:12   File "/app/saleor/graphql/product/mutations/product/product_media_create.py", line 100, in perform_mutation
2023-03-27 15:44:12     media = product.media.create(
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 677, in create
2023-03-27 15:44:12     return super(RelatedManager, self.db_manager(db)).create(**kwargs)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2023-03-27 15:44:12     return getattr(self.get_queryset(), name)(*args, **kwargs)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
2023-03-27 15:44:12     obj.save(force_insert=True, using=self.db)
2023-03-27 15:44:12   File "/app/saleor/core/models.py", line 32, in save
2023-03-27 15:44:12     super().save(*args, **kwargs)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
2023-03-27 15:44:12     self.save_base(using=using, force_insert=force_insert,
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
2023-03-27 15:44:12     updated = self._save_table(
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
2023-03-27 15:44:12     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
2023-03-27 15:44:12     return manager._insert(
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2023-03-27 15:44:12     return getattr(self.get_queryset(), name)(*args, **kwargs)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
2023-03-27 15:44:12     return query.get_compiler(using=using).execute_sql(returning_fields)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
2023-03-27 15:44:12     for sql, params in self.as_sql():
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
2023-03-27 15:44:12     value_rows = [
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
2023-03-27 15:44:12     [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
2023-03-27 15:44:12     [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1310, in pre_save_val
2023-03-27 15:44:12     return field.pre_save(obj, add=True)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/files.py", line 302, in pre_save
2023-03-27 15:44:12     file.save(file.name, file.file, save=False)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/files.py", line 89, in save
2023-03-27 15:44:12     self.name = self.storage.save(name, content, max_length=self.field.max_length)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/django/core/files/storage.py", line 54, in save
2023-03-27 15:44:12     name = self._save(name, content)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/storages/backends/s3boto3.py", line 445, in _save
2023-03-27 15:44:12     obj.upload_fileobj(content, ExtraArgs=params, Config=self._transfer_config)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/boto3/s3/inject.py", line 725, in object_upload_fileobj
2023-03-27 15:44:12     return self.meta.client.upload_fileobj(
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/boto3/s3/inject.py", line 636, in upload_fileobj
2023-03-27 15:44:12     return future.result()
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/s3transfer/futures.py", line 103, in result
2023-03-27 15:44:12     return self._coordinator.result()
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/s3transfer/futures.py", line 266, in result
2023-03-27 15:44:12     raise self._exception
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/s3transfer/tasks.py", line 139, in __call__
2023-03-27 15:44:12     return self._execute_main(kwargs)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/s3transfer/tasks.py", line 162, in _execute_main
2023-03-27 15:44:12     return_value = self._main(**kwargs)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/s3transfer/upload.py", line 758, in _main
2023-03-27 15:44:12     client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
2023-03-27 15:44:12     return self._make_api_call(operation_name, kwargs)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 943, in _make_api_call
2023-03-27 15:44:12     http, parsed_response = self._make_request(
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 966, in _make_request
2023-03-27 15:44:12     return self._endpoint.make_request(operation_model, request_dict)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 119, in make_request
2023-03-27 15:44:12     return self._send_request(request_dict, operation_model)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 198, in _send_request
2023-03-27 15:44:12     request = self.create_request(request_dict, operation_model)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 134, in create_request
2023-03-27 15:44:12     self._event_emitter.emit(
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit
2023-03-27 15:44:12     return self._emitter.emit(aliased_event_name, **kwargs)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit
2023-03-27 15:44:12     return self._emit(event_name, kwargs)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit
2023-03-27 15:44:12     response = handler(**kwargs)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/signers.py", line 105, in handler
2023-03-27 15:44:12     return self.sign(operation_name, request)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/signers.py", line 189, in sign
2023-03-27 15:44:12     auth.add_auth(request)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/auth.py", line 432, in add_auth
2023-03-27 15:44:12     self._inject_signature_to_request(request, signature)
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/auth.py", line 435, in _inject_signature_to_request
2023-03-27 15:44:12     auth_str = ['AWS4-HMAC-SHA256 Credential=%s' % self.scope(request)]
2023-03-27 15:44:12   File "/usr/local/lib/python3.9/site-packages/botocore/auth.py", line 384, in scope
2023-03-27 15:44:12     return '/'.join(scope)
2023-03-27 15:44:12 TypeError: sequence item 0: expected str instance, NoneType found
2023-03-27 19:50:52 2023-03-27 17:50:52,745 INFO saleor.graphql.errors.handled A query had an error [PID:27:ThreadPoolExecutor-0_0]
2023-03-27 19:50:52 Traceback (most recent call last):
2023-03-27 19:50:52   File "/app/saleor/graphql/views.py", line 321, in execute_graphql_request
2023-03-27 19:50:52     response = document.execute(
2023-03-27 19:50:52   File "/usr/local/lib/python3.9/site-packages/graphql/backend/core.py", line 32, in execute_and_validate
2023-03-27 19:50:52     return execute(schema, document_ast, *args, **kwargs)
2023-03-27 19:50:52   File "/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py", line 113, in execute
2023-03-27 19:50:52     exe_context = ExecutionContext(
2023-03-27 19:50:52   File "/usr/local/lib/python3.9/site-packages/graphql/execution/utils.py", line 113, in __init__
2023-03-27 19:50:52     variable_values = get_variable_values(
2023-03-27 19:50:52   File "/usr/local/lib/python3.9/site-packages/graphql/execution/values.py", line 74, in get_variable_values
2023-03-27 19:50:52     raise GraphQLError(
2023-03-27 19:50:52 graphql.error.base.GraphQLError: Variable "$input" got invalid value [{"channelId": "Q2hhbm5lbDoy", "costPrice": null, "price": ""}].
2023-03-27 19:50:52 In element #0: In field "price": Expected type "PositiveDecimal", found "".
2023-03-27 19:50:52 2023-03-27 17:50:52,746 WARNING django.request Bad Request: /graphql/ [PID:27:ThreadPoolExecutor-42_0]
2023-03-27 19:51:02 2023-03-27 17:51:02,698 ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:27:ThreadPoolExecutor-0_0]
2023-03-27 19:51:02 Traceback (most recent call last):
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
2023-03-27 19:51:02     return executor.execute(resolve_fn, source, info, **args)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/graphql/execution/executors/sync.py", line 16, in execute
2023-03-27 19:51:02     return fn(*args, **kwargs)
2023-03-27 19:51:02   File "/app/saleor/graphql/core/mutations.py", line 517, in mutate
2023-03-27 19:51:02     response = cls.perform_mutation(root, info, **data)
2023-03-27 19:51:02   File "/app/saleor/graphql/product/mutations/product/product_media_create.py", line 100, in perform_mutation
2023-03-27 19:51:02     media = product.media.create(
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 677, in create
2023-03-27 19:51:02     return super(RelatedManager, self.db_manager(db)).create(**kwargs)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2023-03-27 19:51:02     return getattr(self.get_queryset(), name)(*args, **kwargs)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
2023-03-27 19:51:02     obj.save(force_insert=True, using=self.db)
2023-03-27 19:51:02   File "/app/saleor/core/models.py", line 32, in save
2023-03-27 19:51:02     super().save(*args, **kwargs)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
2023-03-27 19:51:02     self.save_base(using=using, force_insert=force_insert,
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
2023-03-27 19:51:02     updated = self._save_table(
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
2023-03-27 19:51:02     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
2023-03-27 19:51:02     return manager._insert(
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2023-03-27 19:51:02     return getattr(self.get_queryset(), name)(*args, **kwargs)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
2023-03-27 19:51:02     return query.get_compiler(using=using).execute_sql(returning_fields)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
2023-03-27 19:51:02     for sql, params in self.as_sql():
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
2023-03-27 19:51:02     value_rows = [
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
2023-03-27 19:51:02     [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
2023-03-27 19:51:02     [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1310, in pre_save_val
2023-03-27 19:51:02     return field.pre_save(obj, add=True)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/files.py", line 302, in pre_save
2023-03-27 19:51:02     file.save(file.name, file.file, save=False)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/files.py", line 89, in save
2023-03-27 19:51:02     self.name = self.storage.save(name, content, max_length=self.field.max_length)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/django/core/files/storage.py", line 54, in save
2023-03-27 19:51:02     name = self._save(name, content)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/storages/backends/s3boto3.py", line 445, in _save
2023-03-27 19:51:02     obj.upload_fileobj(content, ExtraArgs=params, Config=self._transfer_config)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/boto3/s3/inject.py", line 725, in object_upload_fileobj
2023-03-27 19:51:02     return self.meta.client.upload_fileobj(
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/boto3/s3/inject.py", line 636, in upload_fileobj
2023-03-27 19:51:02     return future.result()
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/s3transfer/futures.py", line 103, in result
2023-03-27 19:51:02     return self._coordinator.result()
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/s3transfer/futures.py", line 266, in result
2023-03-27 19:51:02     raise self._exception
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/s3transfer/tasks.py", line 139, in __call__
2023-03-27 19:51:02     return self._execute_main(kwargs)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/s3transfer/tasks.py", line 162, in _execute_main
2023-03-27 19:51:02     return_value = self._main(**kwargs)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/s3transfer/upload.py", line 758, in _main
2023-03-27 19:51:02     client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
2023-03-27 19:51:02     return self._make_api_call(operation_name, kwargs)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 943, in _make_api_call
2023-03-27 19:51:02     http, parsed_response = self._make_request(
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 966, in _make_request
2023-03-27 19:51:02     return self._endpoint.make_request(operation_model, request_dict)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 119, in make_request
2023-03-27 19:51:02     return self._send_request(request_dict, operation_model)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 198, in _send_request
2023-03-27 19:51:02     request = self.create_request(request_dict, operation_model)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 134, in create_request
2023-03-27 19:51:02     self._event_emitter.emit(
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit
2023-03-27 19:51:02     return self._emitter.emit(aliased_event_name, **kwargs)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit
2023-03-27 19:51:02     return self._emit(event_name, kwargs)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit
2023-03-27 19:51:02     response = handler(**kwargs)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/signers.py", line 105, in handler
2023-03-27 19:51:02     return self.sign(operation_name, request)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/signers.py", line 189, in sign
2023-03-27 19:51:02     auth.add_auth(request)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/auth.py", line 432, in add_auth
2023-03-27 19:51:02     self._inject_signature_to_request(request, signature)
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/auth.py", line 435, in _inject_signature_to_request
2023-03-27 19:51:02     auth_str = ['AWS4-HMAC-SHA256 Credential=%s' % self.scope(request)]
2023-03-27 19:51:02   File "/usr/local/lib/python3.9/site-packages/botocore/auth.py", line 384, in scope
2023-03-27 19:51:02     return '/'.join(scope)
2023-03-27 19:51:02 TypeError: sequence item 0: expected str instance, NoneType found
```

### Environment

Saleor version: 3.12.0
OS and version: Ubuntu 22.04

I'm using the `saleor/platform` repo locally with the following env values:

```
DATABASE_URL=postgres://saleor:saleor@db/saleor
DEFAULT_FROM_EMAIL=saleor-stage@<MY_DOMAIN>
CELERY_BROKER_URL=redis://redis:6379/1
SECRET_KEY=<MY_SECRET_KEY>
DEBUG=True
ENABLE_DEBUG_TOOLBAR=True
EMAIL_URL=smtp://saleor-stage@<MY_DOMAIN>:<SMTP_PASS>@<SMTP_HOST>:465/?ssl=True
ALLOWED_HOSTS=localhost,api,<THIRD_PARTY_URL>
DEFAULT_COUNTRY=AT
DEFAULT_CURRENCY=EUR
# AWS
AWS_ACCES_KEY_ID="<AWS_ACCESS_KEY>"
AWS_SECRET_ACCESS_KEY="<AWS_SECRET_ACCESS_KEY>"
AWS_MEDIA_BUCKET_NAME="<MEDIA_BUCKET_NAME>"
AWS_MEDIA_CUSTOM_DOMAIN="<MEDIA_CUSTOM_DOMAIN>"
AWS_STORAGE_BUCKET_NAME="<STORAGE_BUCKET_NAME>"
AWS_STORAGE_CUSTOM_DOMAIN="<STORAGE_CUSTOM_DOMAIN>"
AWS_S3_FILE_OVERWRITE=True
AWS_DEFAULT_ACL=bucket-owner-full-control
```

**Comment by veve178** [comment]
i can reproduce the same issue

**Comment by patrys** [comment]
Something is wrong with your AWS S3 config, but I can't tell what exactly from the stack trace in the first message. Please post additional details and see if removing the `AWS_DEFAULT_ACL` helps, as that ACL would prevent anyone from accessing the uploaded files.

**Comment by drazenbebic** [comment]
@patrys Thanks for your reply!

I have tried removing `AWS_DEFAULT_ACL` but that didn't do anything. Do I have to remove any Docker volumes before I recreate the containers?

Also: The AWS User has the `AdministratorAccess` policy (for testing purposes):

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

I checked in IAM on the Amazon console to see if Amazon identified any activity with the key, but nope:

![image](https://user-images.githubusercontent.com/26099016/229100376-ad71355c-44c3-40d3-b463-f48e3ea34721.png)

**Comment by drazenbebic** [comment]
And the ACL is set to `bucket-owner-full-control` on purpose, because I've set up a CloudFront instance which serves the S3 files. I have already tested this and it works.

Before I started playing with the S3 config I had the default media storage (inside the docker container). Then I added the .env entries and recreated the containers. Immediately I got a bunch of 404's in the backend, because the Dashboard can't find the files. However it did use the `AWS_MEDIA_CUSTOM_DOMAIN` env file I passed, meaning that it tried to serve the files from CloudFront. When I uploaded them there manually it worked.

The only issue is that I can't seem to upload any files to the bucket, the other part seems to work fine.

**Comment by patrys** [comment]
CC @NyanKiyoshi @magul @cmiacz, maybe one of you has an idea? I don't know why the boto scope would be null at that place. I'd start with tracing the call to see at which point scopes are determined and why one of them ends up being `None`, but I didn't have the time to do it.

**Comment by NyanKiyoshi** [comment]
Hi @drazenbebic, on the first message you sent there is a typo `AWS_ACCES_KEY_ID`, it should be `AWS_ACCESS_KEY_ID`.

Based on the code from traceback, you are missing the AWS access key: https://github.com/boto/botocore/blob/2baa022100f8fdb4d65fe3b902ac40b415bbeebe/botocore/auth.py#L379

**Comment by drazenbebic** [comment]
@NyanKiyoshi Thank you very much! That was the issue. Can't believe I didn't catch it myself...

I'm almost certain that I copy-pasted a config block from somewhere and edited the values myself, but I'm not a 100% sure. I checked the docs and there it's spelled correctly, so it must have been somewhere else.

Thanks again! :)

**Comment by nnthuanegany** [comment]
Hi @drazenbebic,

I have a discussions : https://github.com/saleor/saleor/discussions/15055 for details:

I am configuring S3 for Saleor 3x, as below

Docs: https://docs.saleor.io/docs/3.x/setup/media-s3#serving-media-files-from-an-s3-bucket

```bash
export MEDIA_URL="https://mycdn.com/saleor/media/"
export STATIC_URL="https://mycdn.com/saleor/static/"
export AWS_ACCESS_KEY_ID="my_id"
export AWS_SECRET_ACCESS_KEY="my_key"
export AWS_DEFAULT_ACL="public-read"
export AWS_MEDIA_BUCKET_NAME="my_bucket_name"
export AWS_MEDIA_CUSTOM_DOMAIN="https://mycdn.com"
export AWS_QUERYSTRING_AUTH="True"
export AWS_QUERYSTRING_EXPIRE="30"
export AWS_STATIC_CUSTOM_DOMAIN="https://mycdn.com"
export AWS_STORAGE_BUCKET_NAME="my_bucket_name"
```

I don't know when there will be https or just domain.

And for custom domains, does it include the path (subfolder) or not?...

Can you send me a sample configuration? Thank you!
