### ISSUE TITLE
Bug: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#13763]
### What are you trying to achieve?

I'm testing the `orderBulkCreate` mutation. When passing `createdAt` that uses incorrect format, a Python exception is raised.

### Steps to reproduce the problem

Example mutation with a value `createdAt: "2023-08-23T08:58:47"`:

```graphql
mutation {
  orderBulkCreate(
    errorPolicy: REJECT_EVERYTHING
    stockUpdatePolicy: SKIP
    orders: [
      {
        channel: "default-channel",
        createdAt: "2023-08-23T08:58:47",
        user: {
          email: "test@example.com"},
        currency: "USD",
        billingAddress: {
          firstName: "test",
          lastName: "test",
          streetAddress1: "test",
          postalCode: "12-123",
          city: "test",
          country: PL
        },
        languageCode: EN,
        lines: []
      }
    ]
  ) {
    count
    results {
      order {
        id
      }
      errors {
        path
        message
      }
    }
    errors {
      path
      message
    }
  }
}
```

Result:
```
2023-08-23 09:16:21,537 ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:14670:ThreadPoolExecutor-0_0]
Traceback (most recent call last):
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/marcin/mirumee/saleor-platform/saleor/saleor/graphql/core/mutations.py", line 540, in mutate
    response = cls.perform_mutation(root, info, **data)
  File "/Users/marcin/mirumee/saleor-platform/saleor/saleor/graphql/order/bulk_mutations/order_bulk_create.py", line 2199, in perform_mutation
    orders_data.append(cls.create_single_order(order_input, object_storage))
  File "/Users/marcin/mirumee/saleor-platform/saleor/saleor/graphql/order/bulk_mutations/order_bulk_create.py", line 1827, in create_single_order
    cls.validate_order_input(order_input, order_data, object_storage)
  File "/Users/marcin/mirumee/saleor-platform/saleor/saleor/graphql/order/bulk_mutations/order_bulk_create.py", line 768, in validate_order_input
    if date and not cls.is_datetime_valid(date):
  File "/Users/marcin/mirumee/saleor-platform/saleor/saleor/graphql/order/bulk_mutations/order_bulk_create.py", line 751, in is_datetime_valid
    return date < timezone.now() + timedelta(minutes=MINUTES_DIFF)
TypeError: can't compare offset-naive and offset-aware datetimes
```

### What did you expect to happen?

A handled validation error should be returned informing that the provided datetime is invalid. Error message could include information about expected format.

### Environment

Saleor version: 3.15

**Comment by maarcingebala** [comment]
BTW after passing correct datetime, the above query also fails:
```
2023-08-23 09:19:45,104 ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:14670:ThreadPoolExecutor-0_0]
Traceback (most recent call last):
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/marcin/mirumee/saleor-platform/saleor/saleor/graphql/core/mutations.py", line 540, in mutate
    response = cls.perform_mutation(root, info, **data)
  File "/Users/marcin/mirumee/saleor-platform/saleor/saleor/graphql/order/bulk_mutations/order_bulk_create.py", line 2199, in perform_mutation
    orders_data.append(cls.create_single_order(order_input, object_storage))
  File "/Users/marcin/mirumee/saleor-platform/saleor/saleor/graphql/order/bulk_mutations/order_bulk_create.py", line 1874, in create_single_order
    cls.validate_order_status(order_input["status"], order_data)
KeyError: 'status'
```

**Comment by Madhan13K** [comment]
Hi @maarcingebala, I tried to reproduce the issue with the above sample data in the GraphQL Playground, I am getting this below error:
 "message": "To access this path, you need one of the following permissions: MANAGE_ORDERS_IMPORT",

So can you please let me know how to get the access for above and I have logged into the saleor as SuperUser.

**Comment by SulavAdhikari** [comment]
I want to work on this. Can you assign it to me, @maarcingebala ?

**Comment by Madhan13K** [comment]
Hi @maarcingebala , createdAt data being passed is in off-naive it has to changed to offset-aware, so can you please provide the details to which timezone it has to be changed?

**Comment by wassafshahzad** [comment]
@maarcingebala Can I work on this ?

**Comment by maarcingebala** [comment]
No one from our team is currently working on it so you can go ahead!

**Comment by zedzior** [comment]
According to [RFC](https://github.com/saleor/saleor/issues/11870) `status` should be required input field.

**Comment by maarcingebala** [comment]
Since this API is in Feature Preview I think we should make the status field required in the schema and mark that as a breaking change.

**Comment by maarcingebala** [comment]
Second issue moved here: https://github.com/saleor/saleor/issues/14506
