### ISSUE TITLE
Bug: Field 'id' expected a number but got UUID

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#14253]
### What are you trying to achieve?

Call the `shippingMethodChannelListingUpdate` mutation with an invalid ID. Example:

```
mutation MyMutation {
  shippingMethodChannelListingUpdate(
    id: "Q2hlY2tvdXQ6YzM2ZGY1NGQtN2NkMi00ZTA0LTkyMjEtYzA5NmY1ZmZjODk5"
    input: {addChannels: {channelId: "default-channel"}}
  ) {
    shippingMethod {
      description
      channelListings {
        id
        channel {
          availableShippingMethodsPerCountry(countries: AF) {
            countryCode
            shippingMethods {
              active
              description
              id
              maximumDeliveryDays
              message
            }
          }
        }
      }
    }
  }
}
```

The `id` is invalid for this mutation as it points to a checkout, but the mutation doesn't validate it. As a result, the mutation crashes with a Python error:

```
Traceback (most recent call last):
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "./saleor/graphql/core/mutations.py", line 527, in mutate
    response = cls.perform_mutation(root, info, **data)
  File "./saleor/graphql/shipping/mutations/channels.py", line 263, in perform_mutation
    shipping_method = get_shipping_model_by_object_id(id)
  File "./saleor/graphql/shipping/utils.py", line 24, in get_shipping_model_by_object_id
    shipping_method = ShippingMethod.objects.filter(pk=object_pk).first()
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1370, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1216, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/django/db/models/lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/django/db/models/lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/marcin/.pyenv/versions/3.9.1/envs/saleor/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'c36df54d-7cd2-4e04-9221-c096f5ffc899'.
```

By briefly looking at code, the issue should be fixed in the `get_shipping_model_by_object_id` - it calls `from_global_id_or_error` internally and we should most likely change it to:

```
from_global_id_or_error(
    object_id, only_type="ShippingMethodType", raise_error=raise_error
)
```

Things to check:
- whether this change wouldn't break other usages of `get_shipping_model_by_object_id`
- whether it expects `ShippingMethodType` or `ShippingMethod` - most likely the first one, as this is the type used by admin mutations, while `ShippingMethod` is used in public API.

### Steps to reproduce the problem

1. See mutation above.

### What did you expect to happen?

The mutation should not crash, it should return a validation error or a GraphQL error.

### Environment

Saleor version: 3.14 and higher.

**Comment by aniav** [comment]
I checked and this is no longer an issue on 3.20 🎉
