### ISSUE TITLE
Change value of Django parameter DATA_UPLOAD_MAX_MEMORY_SIZE

### ISSUE THREAD

**Issue by pawelromanskidajar** [saleor/saleor#15354]
## Problem

I get following error when I try upload file of size over 2.5MB: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/app/saleor/asgi/cors_handler.py", line 112, in cors_wrapper
    await application(scope, receive, send_with_origin)
  File "/app/saleor/asgi/gzip_compression.py", line 142, in gzip_compression_wrapper
    await app(scope, receive, send_compressed)
  File "/app/saleor/asgi/health_check.py", line 16, in health_check_wrapper
    await application(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/asgi.py", line 83, in sentry_patched_asgi_handler
    return await middleware(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 146, in _run_asgi3
    return await self._run_app(scope, receive, send, asgi_version=3)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 241, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 234, in _run_app
    return await self.app(
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/asgi.py", line 156, in __call__
    request, error_response = self.create_request(scope, body_file)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/asgi.py", line 104, in sentry_patched_create_request
    _ = request.body
  File "/usr/local/lib/python3.9/site-packages/django/http/request.py", line 335, in body
    raise RequestDataTooBig('Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.')
django.core.exceptions.RequestDataTooBig: Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
```

---

### Acceptance Criteria

Setting environment variable DATA_UPLOAD_MAX_MEMORY_SIZE should change Django parameter

## 2. API changes

No API changes

## 3. Database changes

No database changes

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add DATA_UPLOAD_MAX_MEMORY_SIZE  to saleor/settings.py
- [ ] Add explanation of parameter DATA_UPLOAD_MAX_MEMORY_SIZE  to documentation
```

## 6. To Test

- Verify uploading larger photos after increased value of DATA_UPLOAD_MAX_MEMORY_SIZE

**Comment by maarcingebala** [comment]
Reproduced on Saleor 3.19.0-a (master.staging) by trying to upload product image of size 2.7MB. Sentry log: https://saleor.sentry.io/issues/4968485679/events/fd74f4f6a4b94333be09f3f0de958876/

**Comment by IKarbowiak** [comment]
Hi @pawelromanskidajar,
The error was raised because of [bug](https://github.com/getsentry/sentry-python/issues/2508) in v1.35 of `sentry-sdk`. It's working correctly on the main branch. I prepared the PR for fixing 3.19.
