### ISSUE TITLE
Bug: Installation Problem with window 10

### ISSUE THREAD

**Issue by Bgajapati** [saleor/saleor#15413]
### What are you trying to achieve?

I am trying with saleor 3.16.21  and getting below error:

Traceback (most recent call last):
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception       
    raise _exception[1]
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "E:\Work\Backend\saleor-3.16.21\saleor\plugins\apps.py", line 20, in ready
    self.load_and_check_plugin(plugin_path)
  File "E:\Work\Backend\saleor-3.16.21\saleor\plugins\apps.py", line 26, in load_and_check_plugin
    raise (ImportError(f"Failed to import plugin {plugin_path}: {e}"))
ImportError: Failed to import plugin saleor.plugins.avatax.plugin.AvataxPlugin: DLL load failed while importing _rust: The specified procedure could not be found.

### Steps to reproduce the problem

I am trying with saleor 3.16.21  and getting below error:

Traceback (most recent call last):
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception       
    raise _exception[1]
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "E:\Work\Backend\saleor-3.16.21\saleor\plugins\apps.py", line 20, in ready
    self.load_and_check_plugin(plugin_path)
  File "E:\Work\Backend\saleor-3.16.21\saleor\plugins\apps.py", line 26, in load_and_check_plugin
    raise (ImportError(f"Failed to import plugin {plugin_path}: {e}"))
ImportError: Failed to import plugin saleor.plugins.avatax.plugin.AvataxPlugin: DLL load failed while importing _rust: The specified procedure could not be found.

### What did you expect to happen?

I am trying with saleor 3.16.21  and getting below error:

Traceback (most recent call last):
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception       
    raise _exception[1]
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\91939\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "E:\Work\Backend\saleor-3.16.21\saleor\plugins\apps.py", line 20, in ready
    self.load_and_check_plugin(plugin_path)
  File "E:\Work\Backend\saleor-3.16.21\saleor\plugins\apps.py", line 26, in load_and_check_plugin
    raise (ImportError(f"Failed to import plugin {plugin_path}: {e}"))
ImportError: Failed to import plugin saleor.plugins.avatax.plugin.AvataxPlugin: DLL load failed while importing _rust: The specified procedure could not be found.

### Environment

Saleor version:  3.16.21
OS and version: window 10

**Comment by aniav** [comment]
Hey @Bgajapati sorry for the late response. We aren't really able to help with direct installation on Windows. We recommend using docker as it's quite possible Saleor does not work with Windows at all 🙌 

https://docs.saleor.io/setup/docker-compose
