### ISSUE TITLE
Bug: Error: ModuleNotFoundError: No module named 'setuptools.command.test' when setting up Saleor Core with Docker

### ISSUE THREAD

**Issue by DevAlbinJo** [saleor/saleor#16448]
### What are you trying to achieve?

I am encountering an error while trying to set up Saleor Core on my local machine using Docker. The error occurs during the poetry install process.

### Steps to reproduce the problem

- Clone the Saleor repository.
- Navigate to the project directory.
- Run` docker build -t <docker-image-tag> .`

### What did you expect to happen?

Docker image should be created

### Logs

72.02   • Installing types-pyopenssl (24.1.0.20240722)
72.19   • Installing types-pytz (2024.1.0.20240417)
72.27   • Installing types-pyyaml (6.0.12.20240311)
72.36   • Installing types-urllib3 (1.26.25.14)
72.49   • Installing uvloop (0.19.0)
72.63   • Installing vcrpy (6.0.1)
73.50   • Installing watchfiles (0.22.0)
73.64   • Installing wcmatch (8.5.2)
73.88   • Installing websockets (12.0)
74.42 
74.42   ChefBuildError
74.42 
74.42   Backend subprocess exited when trying to invoke get_requires_for_build_wheel
74.42   
74.42   Traceback (most recent call last):
74.42     File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
74.42       main()
74.42     File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
74.42       json_out["return_val"] = hook(**hook_input["kwargs"])
74.42     File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 134, in get_requires_for_build_wheel
74.42       return hook(config_settings)
74.42     File "/tmp/tmpuirdbgkf/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
74.42       return self._get_build_requires(config_settings, requirements=[])
74.42     File "/tmp/tmpuirdbgkf/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
74.42       self.run_setup()
74.42     File "/tmp/tmpuirdbgkf/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 497, in run_setup
74.42       super().run_setup(setup_script=setup_script)
74.42     File "/tmp/tmpuirdbgkf/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
74.42       exec(code, locals())
74.42     File "<string>", line 9, in <module>
74.42   ModuleNotFoundError: No module named 'setuptools.command.test'
74.42   
74.42 
74.42   at /usr/local/lib/python3.9/site-packages/poetry/installation/chef.py:166 in _prepare
74.44       162│ 
74.44       163│                 error = ChefBuildError("\n\n".join(message_parts))
74.44       164│ 
74.44       165│             if error is not None:
74.44     → 166│                 raise error from None
74.44       167│ 
74.44       168│             return path
74.44       169│ 
74.44       170│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
74.44 
74.44 Note: This error originates from the build backend, and is likely not a problem with poetry but with vcrpy (6.0.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "vcrpy (==6.0.1)"'.
74.44 
------
Dockerfile:15
--------------------
  13 |     RUN poetry config virtualenvs.create false
  14 |     COPY poetry.lock pyproject.toml /app/
  15 | >>> RUN --mount=type=cache,mode=0755,target=/root/.cache/pypoetry poetry install --no-root
  16 |     
  17 |     ### Final image
--------------------
ERROR: failed to solve: process "/bin/sh -c poetry install --no-root" did not complete successfully: exit code: 1

### Environment

Saleor version: 3.20.6

Operating System: Ubuntu 22.04.3 LTS
Python Version: 3.9.18

**Comment by aniav** [comment]
This isn't Saleor's fault. See https://github.com/pypa/setuptools/issues/4519#issuecomment-2254983472. There is a workaround linked there 🙌
