### ISSUE TITLE
Bug: Unable to add Django RESTful API to saleor codebase

### ISSUE THREAD

**Issue by Sheila312** [saleor/saleor#16522]
### What are you trying to achieve?

I know that saleor only supports GraphQL API. However, in my project, I need to support some Restful API for old mobile apps. Is there any way I could add django rest framework into saleor codebase (I am using saleor version 3.20.11)
When I try to add django rest framework into saleor code base. The error below happens when I test RESTful API

### Steps to reproduce the problem

1. Install django-rest-framework
2. Add below data in INSTALLED_APPS in settings.py file
- "django.contrib.auth"
- "rest_framework"
3. Create test api (GET request)
4. Error happens
`django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: auth`
5. I delete the settings "django.contrib.auth". The app runs successfully but when I call RESTful API, this below error happens
`RuntimeError: Model class django.contrib.auth.models.Permission doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

### What did you expect to happen?

I expect to add Django rest framework to saleor framework successfully so that I could support old mobile application

### Logs

Error log in step 4 
`Traceback (most recent call last):
  File "/opt/anaconda3/envs/saleor/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/envs/saleor/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: auth`

Error log in step 6
`Model class django.contrib.auth.models.Permission doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS. - Traceback (most recent call last):
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/rest_framework/request.py", line 390, in _authenticate
    self._not_authenticated()
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/rest_framework/request.py", line 400, in _not_authenticated
    if api_settings.UNAUTHENTICATED_USER:
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/rest_framework/settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/opt/anaconda3/envs/saleor/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/django/contrib/auth/models.py", line 35, in <module>
    class Permission(models.Model):
  File "/opt/anaconda3/envs/saleor/lib/python3.9/site-packages/django/db/models/base.py", line 113, in __new__
    raise RuntimeError(
RuntimeError: Model class django.contrib.auth.models.Permission doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

### Environment

Saleor version: 3.20.11
OS and version: MacOS 14.1
Django Rest framework: 3.14.0

**Comment by maarcingebala** [comment]
By default, Saleor is incompatible with the Django REST framework, and we're not planning to support it. I see three options you could consider:
- fork Saleor and adjust it to work with the REST framework, but I have no idea how much work that would be. I see that `saleor.auth` module conflicts with `django.contrib.auth` (which we don't use) so the question is if REST framework requires `django.contrib.auth` or could be adjusted to use some custom solution. You would have to explore this path but maybe it's possible.
- consider an alternative to the REST framework and try to plug in some simpler and smaller frameworks for REST APIs
- depending on how many endpoints you need to support, maybe you could add Django views that return JSON responses and handle your mobile app. You can plug custom views into `saleor/urls.py`.

This is how Saleor is designed so I'll close the ticket as this is not a bug, but feel free to continue the discussion.
