### ISSUE TITLE
Manual installation of saleor on windows error

### ISSUE THREAD

**Issue by Hasnainhanifse** [saleor/saleor#16820]
Hello sir, i have installed prerequisites and while running `poetry install` command, some dependencies are failing to install.
These are the logs.
`
Installing dependencies from lock file

Package operations: 228 installs, 6 updates, 0 removals

  - Installing mdurl (0.1.2)
  - Installing pyasn1 (0.6.0)
  - Installing six (1.16.0)
  - Installing cachetools (5.3.3)
  - Downgrading idna (3.7 -> 3.6)
  - Installing markdown-it-py (3.0.0)
  - Installing promise (2.3)
  - Installing protobuf (4.25.3)
  - Installing pyasn1-modules (0.4.0)
  - Installing rsa (4.9)
  - Installing rx (1.6.3)
  - Installing uc-micro-py (1.0.3)
  - Downgrading urllib3 (2.2.1 -> 1.26.18)
  - Installing attrs (23.2.0)
  - Installing google-auth (2.29.0)
  - Installing googleapis-common-protos (1.63.0)
  - Installing graphql-core (2.3.2)
  - Installing linkify-it-py (2.0.3)
  - Installing mdit-py-plugins (0.4.0)
  - Installing proto-plus (1.23.0)
  - Installing pycparser (2.22)
  - Installing pygments (2.17.2)
  - Installing rpds-py (0.18.0)
  - Installing typing-extensions (4.10.0)
  - Installing vine (5.1.0)
  - Installing wcwidth (0.2.13)
  - Installing amqp (5.2.0)
  - Installing aniso8601 (7.0.0)
  - Installing asgiref (3.8.1)
  - Installing boltons (21.0.0)                                                                                                                           
  - Installing cffi (1.16.0)                                                                                                                              
  - Installing click (8.1.7)                                                                                                                              
  - Installing exceptiongroup (1.2.0)                                                                                                                     
  - Installing google-api-core (2.18.0)
  - Installing google-crc32c (1.5.0)
  - Installing graphql-relay (2.0.1)
  - Installing grpcio (1.62.1)
  - Installing jmespath (1.0.1)
  - Installing markupsafe (2.1.5)
  - Installing prompt-toolkit (3.0.43)
  - Installing mpmath (1.3.0)
  - Installing python-dateutil (2.9.0.post0)
  - Installing multidict (6.0.5)
  - Installing pytz (2024.1)
  - Installing referencing (0.34.0)
  - Installing rich (13.7.1)
  - Installing sqlparse (0.4.4)
  - Installing sniffio (1.3.1)
  - Installing webencodings (0.5.1)
  - Installing anyio (4.3.0)
  - Installing async-timeout (4.0.3)
  - Installing babel (2.14.0): Pending...
  - Installing babel (2.14.0): Installing...
  - Installing billiard (4.2.0)
  - Installing botocore (1.34.74): Installing...
  - Installing bracex (2.4)
  - Installing brotli (1.1.0)
  - Installing click-didyoumean (0.3.1)
  - Installing click-plugins (1.1.1)
  - Installing click-repl (0.3.0)
  - Installing cryptography (42.0.5): Installing...
  - Installing django (3.2.25): Installing...
  - Installing django (3.2.25): Installing...
  - Installing cryptography (42.0.5)
  - Installing django (3.2.25): Installing...
  - Installing face (22.0.0)
  - Downgrading filelock (3.14.0 -> 3.13.3): Installing...
  - Installing google-cloud-core (2.4.1)
  - Installing google-resumable-media (2.7.0)
  - Installing google-cloud-core (2.4.1)
  - Installing google-resumable-media (2.7.0)
  - Downgrading filelock (3.14.0 -> 3.13.3)
  - Installing google-cloud-core (2.4.1)
  - Installing google-resumable-media (2.7.0)
  - Installing billiard (4.2.0)
  - Installing botocore (1.34.74): Installing...
  - Installing bracex (2.4)
  - Installing brotli (1.1.0)
  - Installing click-didyoumean (0.3.1)
  - Installing click-plugins (1.1.1)
  - Installing click-repl (0.3.0)
  - Installing cryptography (42.0.5)
  - Installing django (3.2.25): Installing...
  - Installing face (22.0.0)
  - Downgrading filelock (3.14.0 -> 3.13.3)
  - Installing google-cloud-core (2.4.1)
  - Installing google-resumable-media (2.7.0)
  - Installing babel (2.14.0)
  - Installing billiard (4.2.0)
  - Installing botocore (1.34.74): Installing...
  - Installing bracex (2.4)
  - Installing brotli (1.1.0)
  - Installing click-didyoumean (0.3.1)
  - Installing click-plugins (1.1.1)
  - Installing click-repl (0.3.0)
  - Installing cryptography (42.0.5)
  - Installing django (3.2.25): Installing...
  - Installing face (22.0.0)
  - Downgrading filelock (3.14.0 -> 3.13.3)
  - Installing google-cloud-core (2.4.1)
  - Installing google-resumable-media (2.7.0)
  - Installing bracex (2.4)
  - Installing brotli (1.1.0)
  - Installing click-didyoumean (0.3.1)
  - Installing click-plugins (1.1.1)
  - Installing click-repl (0.3.0)
  - Installing cryptography (42.0.5)
  - Installing django (3.2.25): Installing...
  - Installing face (22.0.0)
  - Downgrading filelock (3.14.0 -> 3.13.3)
  - Installing google-cloud-core (2.4.1)
  - Installing google-resumable-media (2.7.0)
  - Installing botocore (1.34.74)
  - Installing bracex (2.4)
  - Installing brotli (1.1.0)
  - Installing click-didyoumean (0.3.1)
  - Installing click-plugins (1.1.1)
  - Installing click-repl (0.3.0)
  - Installing cryptography (42.0.5)
  - Installing django (3.2.25): Installing...
  - Installing face (22.0.0)
  - Downgrading filelock (3.14.0 -> 3.13.3)
  - Installing google-cloud-core (2.4.1)
  - Installing google-resumable-media (2.7.0)
  - Installing face (22.0.0)
  - Downgrading filelock (3.14.0 -> 3.13.3)
  - Installing google-cloud-core (2.4.1)
  - Installing google-resumable-media (2.7.0)
  - Installing django (3.2.25)
  - Installing face (22.0.0)
  - Downgrading filelock (3.14.0 -> 3.13.3)
  - Installing google-cloud-core (2.4.1)
  - Installing google-resumable-media (2.7.0)
  - Installing graphene (2.1.9)
  - Installing grpcio-status (1.62.1)
  - Installing iniconfig (2.0.0)
  - Installing jinja2 (3.1.3)
  - Installing jsonschema-specifications (2023.12.1)
  - Downgrading platformdirs (4.2.1 -> 4.2.0)
  - Installing kombu (5.3.6)
  - Installing pluggy (1.4.0)
  - Installing pyyaml (6.0.1)
  - Installing ruamel-yaml-clib (0.2.8)
  - Updating setuptools (49.2.1 -> 69.2.0)
  - Installing singledispatch (4.1.0)
  - Installing soupsieve (2.5)
  - Installing sympy (1.12)
  - Installing text-unidecode (1.3)
  - Installing textual (0.54.0)
  - Installing tinycss2 (1.2.1)
  - Installing tornado (6.4)
  - Installing tzdata (2024.1)
  - Installing wrapt (1.16.0)
  - Installing yarl (1.9.4)
  - Installing zopfli (0.2.3)
  - Installing azure-common (1.1.28)                                                                                                                      
  - Installing azure-core (1.30.1): Installing...                                                                                                         
  - Installing bcrypt (4.1.2)
  - Installing bcrypt (4.1.2)
  - Installing azure-core (1.30.1)
  - Installing bcrypt (4.1.2)
  - Installing beautifulsoup4 (4.7.1)
  - Installing beautifultable (0.7.0)
  - Installing celery (5.3.6): Installing...
  - Installing cfgv (3.4.0)
  - Installing chardet (5.2.0)
  - Installing click-option-group (0.5.6)
  - Installing coverage (7.4.4)
  - Installing cron-descriptor (1.4.3)
  - Installing cssselect2 (0.7.0)
  - Installing defusedxml (0.7.1)
  - Installing django-appconf (1.0.6)
  - Installing django-debug-toolbar (4.3.0): Installing...
  - Installing django-js-asset (2.2.0)
  - Installing django-stubs-ext (4.2.7)
  - Installing django-timezone-field (6.1.0)
  - Installing cfgv (3.4.0)
  - Installing chardet (5.2.0)
  - Installing click-option-group (0.5.6)
  - Installing coverage (7.4.4)
  - Installing cron-descriptor (1.4.3)
  - Installing cssselect2 (0.7.0)
  - Installing defusedxml (0.7.1)
  - Installing django-appconf (1.0.6)
  - Installing django-debug-toolbar (4.3.0): Installing...
  - Installing django-js-asset (2.2.0)
  - Installing django-stubs-ext (4.2.7)
  - Installing django-timezone-field (6.1.0)
  - Installing celery (5.3.6)
  - Installing cfgv (3.4.0)
  - Installing chardet (5.2.0)
  - Installing click-option-group (0.5.6)
  - Installing coverage (7.4.4)
  - Installing cron-descriptor (1.4.3)
  - Installing cssselect2 (0.7.0)
  - Installing defusedxml (0.7.1)
  - Installing django-appconf (1.0.6)
  - Installing django-debug-toolbar (4.3.0): Installing...
  - Installing django-js-asset (2.2.0)
  - Installing django-stubs-ext (4.2.7)
  - Installing django-timezone-field (6.1.0)
  - Installing enmerkar (0.7.1)
  - Installing et-xmlfile (1.1.0)
  - Installing execnet (2.0.2)
  - Installing fonttools (4.50.0): Installing...
  - Installing glom (22.1.0)
  - Installing django-js-asset (2.2.0)
  - Installing django-stubs-ext (4.2.7)
  - Installing django-timezone-field (6.1.0)
  - Installing enmerkar (0.7.1)
  - Installing et-xmlfile (1.1.0)
  - Installing execnet (2.0.2)
  - Installing fonttools (4.50.0): Installing...
  - Installing glom (22.1.0)
  - Installing django-debug-toolbar (4.3.0)
  - Installing django-js-asset (2.2.0)
  - Installing django-stubs-ext (4.2.7)
  - Installing django-timezone-field (6.1.0)
  - Installing enmerkar (0.7.1)
  - Installing et-xmlfile (1.1.0)
  - Installing execnet (2.0.2)
  - Installing fonttools (4.50.0): Installing...
  - Installing glom (22.1.0)
  - Installing google-cloud-storage (2.16.0)
  - Installing graphene-django (2.16.0)
  - Installing grpc-google-iam-v1 (0.13.0)
  - Installing h11 (0.14.0)
  - Installing html5lib (1.1)
  - Installing httptools (0.6.1)
  - Installing identify (2.5.35)
  - Installing isodate (0.6.1)
  - Installing jsonschema (4.21.1)
  - Installing lxml (4.9.4): Installing...
  - Installing measurement (3.2.2)
  - Installing memray (1.11.0): Preparing...
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
  - Installing measurement (3.2.2)
  - Installing memray (1.11.0): Preparing...
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
  - Installing lxml (4.9.4)
  - Installing measurement (3.2.2)
  - Installing memray (1.11.0): Preparing...
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
  - Installing glom (22.1.0)
  - Installing google-cloud-storage (2.16.0)
  - Installing graphene-django (2.16.0)
  - Installing grpc-google-iam-v1 (0.13.0)
  - Installing h11 (0.14.0)
  - Installing html5lib (1.1)
  - Installing httptools (0.6.1)
  - Installing identify (2.5.35)
  - Installing isodate (0.6.1)
  - Installing jsonschema (4.21.1)
  - Installing lxml (4.9.4)
  - Installing measurement (3.2.2)
  - Installing memray (1.11.0): Preparing...
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
  - Installing fonttools (4.50.0)
  - Installing glom (22.1.0)
  - Installing google-cloud-storage (2.16.0)
  - Installing graphene-django (2.16.0)
  - Installing grpc-google-iam-v1 (0.13.0)
  - Installing h11 (0.14.0)
  - Installing html5lib (1.1)
  - Installing httptools (0.6.1)
  - Installing identify (2.5.35)
  - Installing isodate (0.6.1)
  - Installing jsonschema (4.21.1)
  - Installing lxml (4.9.4)
  - Installing measurement (3.2.2)
  - Installing memray (1.11.0): Preparing...
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
  - Installing memray (1.11.0): Failed
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)

  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
  ChefBuildError
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)

  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  pkg-config not found. pkg-config probably not installed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
  Falling back to static flags.
  Traceback (most recent call last):
    File "c:\users\desktop\desktop\saleor\venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 373, in <module>
      main()
    File "c:\users\desktop\desktop\saleor\venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
    File "c:\users\desktop\desktop\saleor\venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 134, in get_requires_for_build_wheel   
      return hook(config_settings)
    File "C:\Users\Desktop\AppData\Local\Temp\tmpxfi0_cri\.venv\lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel    
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\Desktop\AppData\Local\Temp\tmpxfi0_cri\.venv\lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\Desktop\AppData\Local\Temp\tmpxfi0_cri\.venv\lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 291, in <module>
  RuntimeError: memray does not support this platform (win32)
  
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)

  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
  at c:\users\desktop\desktop\saleor\venv\lib\site-packages\poetry\installation\chef.py:164 in _prepare
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
      160│
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
      161│                 error = ChefBuildError("\n\n".join(message_parts))
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
      162│
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
      163│             if error is not None:
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
    → 164│                 raise error from None
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
      165│
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
      166│             return path
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
      167│
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)

  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
Note: This error originates from the build backend, and is likely not a problem with poetry but with memray (1.11.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "memray (==1.11.0)"'.
  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)

  - Installing mock (1.0.1)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.8.0)
  - Installing opentracing (2.4.0)
  - Installing pathspec (0.12.1)
  - Installing peewee (3.17.1)
  - Installing pillow (10.2.0)
  - Installing prices (1.1.1)
  - Installing pydyf (0.9.0)
  - Installing pymeta3 (0.5.1)
  - Installing pyphen (0.14.0)
  - Installing pytest (8.1.1)
  - Installing python-crontab (3.0.0)
  - Installing python-dotenv (1.0.1)
  - Installing python-http-client (3.3.7)
  - Installing pyxb (1.2.5)
  - Installing redis (5.0.3)
  - Installing ruamel-yaml (0.17.40)
  - Installing s3transfer (0.10.1)
  - Installing sortedcontainers (2.4.0)
  - Installing starkbank-ecdsa (2.2.0)
  - Installing threadloop (1.0.2)
  - Installing thrift (0.20.0)
  - Installing types-pyopenssl (24.0.0.20240311)
  - Installing types-pytz (2024.1.0.20240203)
  - Installing types-pyyaml (6.0.12.20240311)
  - Installing types-urllib3 (1.26.25.14)
  - Installing vcrpy (4.4.0)
  - Downgrading virtualenv (20.26.1 -> 20.25.1)
  - Installing watchfiles (0.21.0)
  - Installing wcmatch (8.5.1)
  - Installing websockets (12.0)
`

**Comment by aniav** [comment]
I will close this for now. We suggest to use docker images with Saleor instead of installing directly on Windows as we do not guarantee it working on Windows.
