### ISSUE TITLE
requirements file is not installing 

### ISSUE THREAD

**Issue by ganeshsingamaneni** [saleor/saleor#3570]
### What I'm trying to achieve
… Trying to install requirements.txt

### Steps to reproduce the problem
1.  pip install -r requirements.txt
Looking in indexes: https://pypi.python.org/simple
Collecting amqp==2.3.2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7f/cf/12d4611fc67babd4ae250c9e8249c5650ae1933395488e9e7e3562b4ff24/amqp-2.3.2-py2.py3-none-any.whl
Collecting aniso8601==3.0.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/17/13/eecdcc638c0ea3b105ebb62ff4e76914a744ef1b6f308651dbed368c6c01/aniso8601-3.0.2-py2.py3-none-any.whl
Collecting autopep8==1.4.3 (from -r requirements.txt (line 4))
Exception:
Traceback (most recent call last):
  File "/home/ganesh/learning/myenv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/home/ganesh/learning/myenv/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/home/ganesh/learning/myenv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/ganesh/learning/myenv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/ganesh/learning/myenv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/home/ganesh/learning/myenv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 283, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/home/ganesh/learning/myenv/lib/python3.6/site-packages/pip/_internal/download.py", line 823, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/home/ganesh/learning/myenv/lib/python3.6/site-packages/pip/_internal/download.py", line 728, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/home/ganesh/learning/myenv/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 582, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/home/ganesh/learning/myenv/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 467, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents

2. 

### What I expected to happen
…

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by Pacu2** [comment]
Please provide a whole stack trace

**Comment by ganeshsingamaneni** [comment]
![screenshot from 2019-01-09 15-19-01](https://user-images.githubusercontent.com/34410056/50891297-f6498380-1421-11e9-94cf-f534920dd1f4.png)

**Comment by Pacu2** [comment]
Could you try removing pip's cache and reinstall the requirements?

**Comment by ganeshsingamaneni** [comment]
![screenshot from 2019-01-09 15-29-52](https://user-images.githubusercontent.com/34410056/50891964-702e3c80-1423-11e9-9b08-795244e54698.png)
This is the result i got

**Comment by Pacu2** [comment]
Have you tried installing `pkg_resources`? 
https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

**Comment by ganeshsingamaneni** [comment]
Yes that worked exactly,
i have installed setup-tools==40.0 earlier that's where the problem occurred, we need setup-tools==39.1.0
