### ISSUE TITLE
Elastic search RequestError when creating index on heroku

### ISSUE THREAD

**Issue by khalibloo** [saleor/saleor#4475]
### What I'm trying to achieve
Create elastic search index with `python manage.py search_index --create` on Heroku using Bonsai (as described in the saleor docs).

### Steps to reproduce the problem
1. Install saleor, add sample data with `populatedb`
2. Provision bonsai addon, create index

### What I expected to happen
The index should have been created. Got the following error `elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [doc : {properties={user_email={type=text}, discount_name={type=text}, last_name={type=text}, user={analyzer=email_analyzer, type=text}, first_name={type=text}}}]')`

### Full console output
```
Creating index 'orders'
WARNING elasticsearch PUT https://xxxxx-xxxxxxxxxxxx.us-east-1.bonsaisearch.net:443/orders [status:400 request:0.041s] [PID:4:MainThread]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.7/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 128, in handle
    self._create(models, options)
  File "/app/.heroku/python/lib/python3.7/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 84, in _create
    index.create()
  File "/app/.heroku/python/lib/python3.7/site-packages/elasticsearch_dsl/index.py", line 203, in create
    self.connection.indices.create(index=self._name, body=self.to_dict(), **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 88, in create
    params=params, body=body)
  File "/app/.heroku/python/lib/python3.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/app/.heroku/python/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/app/.heroku/python/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [doc : {properties={user_email={type=text}, discount_name={type=text}, last_name={type=text}, user={analyzer=email_analyzer, type=text}, first_name={type=text}}}]')
```

**System information**
Operating system: Windows 10 x64
Browser: Firefox 68

**Comment by Tiagorsa** [comment]
@khalibloo 
@maarcingebala 

This is because heroku changed the elasticsarch version on sandbox plan. Since 2019-07-12 the version is 7.2.0 and saleor needs 5.x.x version. I created on AWS to test and works.

![heroku-sandbox-versions](https://user-images.githubusercontent.com/8277086/63609218-1a229980-c5ad-11e9-9017-621437f2cdad.png)


![saleor-heroku-sanddox](https://user-images.githubusercontent.com/8277086/63609229-24449800-c5ad-11e9-8560-f49c5d4b3f49.png)

**Comment by maarcingebala** [comment]
Closing as Elasticsearch is no longer supported.
