### ISSUE TITLE
Runing pytest -h in Saleor raises exception

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#5768]
Moving tests from `saleor/tests` to modules broke `pytest -h`
```
(saleor2) ➜  saleor git:(96613dfb0) ✗ pytest -h
/Users/maciej/Workspace/saleor/saleor/settings.py:203: UserWarning: SECRET_KEY not configured, using a random temporary key.
  warnings.warn("SECRET_KEY not configured, using a random temporary key.")
Traceback (most recent call last):
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 495, in _importconftest
    return self._conftestpath2mod[key]
KeyError: PosixPath('/Users/maciej/Workspace/saleor/conftest.py')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maciej/.virtualenvs/saleor2/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 257, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1001, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 899, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 444, in _set_initial_conftests
    self._try_load_conftest(current)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 447, in _try_load_conftest
    self._getconftestmodules(anchor)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 473, in _getconftestmodules
    mod = self._importconftest(conftestpath)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 520, in _importconftest
    self.consider_conftest(mod)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 575, in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 386, in register
    self.consider_module(plugin)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 581, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 586, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 613, in import_plugin
    __import__(importspec)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "/Users/maciej/Workspace/saleor/saleor/tests/fixtures.py", line 12, in <module>
    from django.contrib.auth.models import Group, Permission
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/django/db/models/base.py", line 107, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/django/apps/registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/maciej/.virtualenvs/saleor2/lib/python3.8/site-packages/django/apps/registry.py", line 135, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by neerajgupta2407** [comment]
I am also getting the same error. Unable to run test suite .
Command: `python -m unittest`

Output:  https://pastebin.com/TagRRZPU

**Comment by neerajgupta2407** [comment]
My Bad...with "pytest", it's working
