### ISSUE TITLE
python manage.py populatedb - Failed with : 'bool' object has no attribute 'strip'

### ISSUE THREAD

**Issue by onelsonic** [saleor/saleor#6714]
Building the current commit with Python 3.9.1 on CENTOS/RHEL8.
when populating the example DB provided with :

`python manage.py populatedb`

I get the following error : 
```
Created footer menu
No sequences found.
No sequences found.
Traceback (most recent call last):
  File "/home/devweb/saleor-platform/saleor/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/devweb/envpyth/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/devweb/envpyth/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/devweb/envpyth/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/devweb/envpyth/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/devweb/saleor-platform/saleor/saleor/core/management/commands/populatedb.py", line 126, in handle
    for msg in create_permission_groups():
  File "/home/devweb/saleor-platform/saleor/saleor/core/utils/random_data.py", line 730, in create_permission_groups
    super_users = create_staff_users(1, True)
  File "/home/devweb/saleor-platform/saleor/saleor/core/utils/random_data.py", line 801, in create_staff_users
    staff_user = _create_staff_user(superuser)
  File "/home/devweb/saleor-platform/saleor/saleor/core/utils/random_data.py", line 784, in _create_staff_user
    staff_user = User.objects.create_user(
  File "/home/devweb/saleor-platform/saleor/saleor/account/models.py", line 110, in create_user
    email = UserManager.normalize_email(email)
  File "/home/devweb/envpyth/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 26, in normalize_email
    email_name, domain_part = email.strip().rsplit('@', 1)
AttributeError: 'bool' object has no attribute 'strip'
```

**Comment by onelsonic** [comment]
I think 
***********User.objects.get(email=email)
should be replaced by

**Comment by techwebdev** [comment]
i got the same how we will fix this

**Comment by krzysztofwolski** [comment]
Does the issue still occur?

**Comment by maarcingebala** [comment]
Please reopen if it's still an issue on newest versions.
