### ISSUE TITLE
Money.resolve_amount(...) expects amount to be a float but tries to get root.amount, root.currency

### ISSUE THREAD

**Issue by LeOndaz** [saleor/saleor#6750]
`createPayment` is a method with this signature 
```
const createPayment = (checkoutId: string, input: PaymentInput, language: ILanguage) => client.mutate({
    mutation: CreatePaymentDocument,
    variables: {
        languageCode: language.code,
        checkoutId,
        input,
    }
})
```
```
createPayment(checkout.id, {
    token: result.token?.id,
    returnUrl: 'http://localhost:3000/',
    amount: checkout.totalPrice.gross.amount,
    gateway: "mirumee.payments.stripe",
}, getDefaultLanguage()).then(r => {
    console.log(r)
})
```

This query document is okay, the problem here is 
```
ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:655:Thread-181]
Traceback (most recent call last):
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/promise/promise.py", line 489, in _resolve_from_executor
    executor(resolve, reject)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/promise/promise.py", line 756, in executor
    return resolve(f(*args, **kwargs))
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "/home/leondaz/crime_scene/backend/core/saleor/graphql/core/types/money.py", line 25, in resolve_amount
    return quantize_price(root.amount, root.currency)
AttributeError: 'decimal.Decimal' object has no attribute 'amount'
[19/Jan/2021 13:47:14] "POST /graphql/ HTTP/1.1" 200 4509
```
And if I remove the ".amount" above, I get the same error, if I make it an object with amount, I get an error with `Expected a decimal, found { "amount": 750 }`

**Comment by LeOndaz** [comment]
How to test: 
```
# graphql/core/types/money.py
   
    class Money(graphene.ObjectType):
        ....
    @staticmethod
    def resolve_amount(root, _info):
        from numbers import Number
        if isinstance(root, Number):
            print(root)

        return quantize_price(root.amount, root.currency)
```
This works! and since it's a number, numbers have no .amount & .currency, most of the time, the `if` statement doesn't execute because root is `Money` (how!) but when it works, an error is thrown  
```
AttributeError: 'decimal.Decimal' object has no attribute 'amount'
```
I'd like to mention that when I checked `isinstance(root, Decimal)` it didn't show up, investigating...

**Comment by LeOndaz** [comment]
The problem is only with the checkoutPaymentCreate mutation
