### ISSUE TITLE
check_stock_quantity_bulk TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by LeOndaz** [saleor/saleor#6772]
My variant is in stock btw
```
ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:2131:ThreadPoolExecutor-0_0]
Traceback (most recent call last):
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/promise/promise.py", line 489, in _resolve_from_executor
    executor(resolve, reject)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/promise/promise.py", line 756, in executor
    return resolve(f(*args, **kwargs))
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "/home/leondaz/crime_scene/backend/core/saleor/graphql/core/mutations.py", line 297, in mutate
    response = cls.perform_mutation(root, info, **data)
  File "/home/leondaz/crime_scene/backend/core/saleor/graphql/checkout/mutations.py", line 381, in perform_mutation
    cleaned_input = cls.clean_input(info, checkout, data.get("input"))
  File "/home/leondaz/crime_scene/backend/core/saleor/graphql/checkout/mutations.py", line 309, in clean_input
    ) = cls.clean_checkout_lines(lines, country, cleaned_input["channel"].id)
  File "/home/leondaz/crime_scene/backend/core/saleor/graphql/checkout/mutations.py", line 225, in clean_checkout_lines
    check_lines_quantity(variants, quantities, country)
  File "/home/leondaz/crime_scene/backend/core/saleor/graphql/checkout/mutations.py", line 121, in check_lines_quantity
    check_stock_quantity_bulk(variants, country, quantities)
  File "/home/leondaz/crime_scene/backend/core/saleor/warehouse/availability.py", line 57, in check_stock_quantity_bulk
    available_quantity = sum([stock.available_quantity for stock in stocks])
TypeError: 'NoneType' object is not iterable
```

**Comment by LeOndaz** [comment]
Okay I've figured out the "why" part, this happens because
```
def check_stock_quantity_bulk(variants, country_code, quantities):
    """Validate if there is stock available for given variants in given country.

    :raises InsufficientStock: when there is not enough items in stock for a variant.
    """
    all_variants_stocks = (
        Stock.objects.for_country(country_code)
        .filter(product_variant__in=variants)
        .annotate_available_quantity()
    )
```
`all_variant_stocks` is empty, and `Stock.objects.for_country(country_code)` also is empty, even though I've warehouses with stocks available
