### ISSUE TITLE
cannot load library 'pango-1.0': dlopen(pango-1.0, 2): image not found

### ISSUE THREAD

**Issue by treasersimplifies** [saleor/saleor#7230]
### What I'm trying to achieve
python manage.py runserver 0.0.0.0:8000

### Steps to reproduce the problem

1. python manage.py runserver 0.0.0.0:8000
2.

### What I expected to happen

start successfully

### Screenshots and logs

```
/Users/treasersmac/Programming/PythonProjects/saleor/saleor/saleor/settings.py:212: UserWarning: SECRET_KEY not configured, using a random temporary key.
  warnings.warn("SECRET_KEY not configured, using a random temporary key.")
/Users/treasersmac/Programming/PythonProjects/saleor/saleor/saleor/settings.py:212: UserWarning: SECRET_KEY not configured, using a random temporary key.
  warnings.warn("SECRET_KEY not configured, using a random temporary key.")
INFO django.utils.autoreload Watching for file changes with StatReloader [PID:5173:MainThread]
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Users/treasersmac/Programming/PythonProjects/saleor/saleor/saleor/plugins/apps.py", line 20, in ready
    self.load_and_check_plugin(plugin_path)
  File "/Users/treasersmac/Programming/PythonProjects/saleor/saleor/saleor/plugins/apps.py", line 24, in load_and_check_plugin
    plugin = import_string(plugin_path)
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/treasersmac/Programming/PythonProjects/saleor/saleor/saleor/plugins/invoicing/plugin.py", line 10, in <module>
    from .utils import generate_invoice_number, generate_invoice_pdf
  File "/Users/treasersmac/Programming/PythonProjects/saleor/saleor/saleor/plugins/invoicing/utils.py", line 8, in <module>
    from weasyprint import HTML
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/weasyprint/__init__.py", line 469, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/weasyprint/css/computed_values.py", line 15, in <module>
    from .. import text
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/weasyprint/text.py", line 260, in <module>
    pango = dlopen(ffi, 'pango-1.0', 'libpango-1.0-0', 'libpango-1.0.so.0',
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/weasyprint/text.py", line 255, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Users/treasersmac/opt/anaconda3/envs/py3_8/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'pango-1.0': dlopen(pango-1.0, 2): image not found.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0'
```

**System information**

Saleor version:
- [X] dev (current master)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [X] MacOS
- [ ] Other

Python Version:
`Python 3.8.8`

**Comment by moch-sudharmono** [comment]
No update?

**Comment by parz3val** [comment]
I ran into the same bug. Installing reinstalling xcode cli tools helped.
You can also try `sudo port install pango` if you haven't already installed it.

**Comment by loveJasmine** [comment]
me too

**Comment by treasersimplifies** [comment]
Hi there,Thank you for your email. I am currently offline and will not have access to email instantly. If this is urgent, please contact me by phone 18258583270. I will do my best to respond promptly to your email when I am on line.Best,

**Comment by jsnbuchanan** [comment]
Me three.

**Comment by maarcingebala** [comment]
Seems like [this might be the solution](https://github.com/saleor/saleor/issues/7230#issuecomment-933253136) if anyone stumbles upon the issue. For now I'm closing this ticket.

**Comment by treasersimplifies** [comment]
Hi there,Thank you for your email. I am currently offline and will not have access to email instantly. If this is urgent, please contact me by phone 18258583270. I will do my best to respond promptly to your email when I am on line.Best,
