### ISSUE TITLE
Extending the schema via federation causes an error found different types with the same name in the schema

### ISSUE THREAD

**Issue by LeOndaz** [saleor/saleor#7276]
Federation service:

```
import {ApolloServer} from 'apollo-server'
import {ApolloGateway} from '@apollo/gateway'

const SALEOR_SERVICE: string = 'http://localhost:8000/graphql/';
const LOCATIONS_SERVICE: string = 'http://localhost:8000/plugins/locations/';


const gateway = new ApolloGateway({
    serviceList: [
        { name: 'Locations Plugin', url: LOCATIONS_SERVICE },
        { name: 'Saleor', url: SALEOR_SERVICE },
    ],
});

const server = new ApolloServer({
    gateway,
    subscriptions: false
});

server.listen(8001).then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});
```

And the extended type is ProductVariant:
```
@extend('id')
class ProductVariant(ObjectType):
    id = external(graphene.ID())
```
And the trace is:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/leondaz/crime_scene/epicore/saleor/saleor/plugins/apps.py", line 20, in ready
    self.load_and_check_plugin(plugin_path)
  File "/home/leondaz/crime_scene/epicore/saleor/saleor/plugins/apps.py", line 24, in load_and_check_plugin
    plugin = import_string(plugin_path)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/leondaz/crime_scene/epicore/saleor/saleor/plugins/locations/plugin.py", line 6, in <module>
    from .graphql.schema import *
  File "/home/leondaz/crime_scene/epicore/saleor/saleor/plugins/locations/graphql/schema.py", line 72, in <module>
    schema = build_schema(LocationQueries, mutation=LocationMutations)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphene_federation/main.py", line 20, in build_schema
    schema = graphene.Schema(query=query, mutation=mutation, **kwargs)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphene/types/schema.py", line 78, in __init__
    self.build_typemap()
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphene/types/schema.py", line 167, in build_typemap
    self._type_map = TypeMap(
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphene/types/typemap.py", line 80, in __init__
    super(TypeMap, self).__init__(types)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphql/type/typemap.py", line 31, in __init__
    self.update(reduce(self.reducer, types, OrderedDict()))  # type: ignore
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphene/types/typemap.py", line 117, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphql/type/typemap.py", line 109, in reducer
    field_map = type_.fields
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphql/pyutils/cached_property.py", line 22, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphql/type/definition.py", line 198, in fields
    return define_field_map(self, self._fields)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphql/type/definition.py", line 212, in define_field_map
    field_map = field_map()
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphene/types/typemap.py", line 275, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphene/types/typemap.py", line 117, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphql/type/typemap.py", line 109, in reducer
    field_map = type_.fields
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphql/pyutils/cached_property.py", line 22, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphql/type/definition.py", line 198, in fields
    return define_field_map(self, self._fields)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphql/type/definition.py", line 212, in define_field_map
    field_map = field_map()
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphene/types/typemap.py", line 275, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/graphene/types/typemap.py", line 97, in graphene_reducer
    assert _type.graphene_type == type, (
AssertionError: Found different types with the same name in the schema: ProductVariant, ProductVariant.
```

possibly related to older issues on federation

**Comment by maarcingebala** [comment]
Does it still happen with the newest version of Saleor? Please reopen if it does.
