### ISSUE TITLE
ERROR: Service 'api' failed to build : The command '/bin/sh -c SECRET_KEY=dummy STATIC_URL=${STATIC_URL} python3 manage.py collectstatic --no-input' returned a non-zero code: 1

### ISSUE THREAD

**Issue by ahmadoji01** [saleor/saleor#7431]
### What I'm trying to achieve
Install Saleon based on the provided documentation

### Steps to reproduce the problem

1. I run the `docker-compose run --rm api python3 manage.py migrate`

### What I expected to happen
I expect the installation to be successful

### Screenshots and logs
Here is the log I received after running that command
```
Step 16/21 : ARG STATIC_URL
 ---> Running in b2c51524839b
Removing intermediate container b2c51524839b
 ---> ec3e96b7fa07
Step 17/21 : ENV STATIC_URL ${STATIC_URL:-/static/}
 ---> Running in ceec7df66b6b
Removing intermediate container ceec7df66b6b
 ---> c434fbc6f03a
Step 18/21 : RUN SECRET_KEY=dummy STATIC_URL=${STATIC_URL} python3 manage.py collectstatic --no-input
 ---> Running in ec65e2dd4120
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/django/contrib/postgres/apps.py", line 1, in <module>
    from psycopg2.extras import (
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libpq.so.5: cannot open shared object file: No such file or directory
ERROR: Service 'api' failed to build : The command '/bin/sh -c SECRET_KEY=dummy STATIC_URL=${STATIC_URL} python3 manage.py collectstatic --no-input' returned a non-zero code: 1
```

**System information**

Saleor version:
- [x] dev (current master)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

What I have tried:
I have tried adding these lines
```
RUN apt-get -y update \
  && apt-get install -y gettext libpq-dev \
  # Cleanup apt cache
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

...
RUN pip install psycopg2 && pip install psycopg2-binary
RUN pip install psycopg2-binary redis>=3.2.0
```

**Comment by masiama** [comment]
@ahmadoji01 I tried adding the same lines you tried – it produced even larger error. However, keeping only `apt-get` step changes and adding `RUN pip install psycopg2-binary` instead of your `pip install` suggestions finally solved this problem for me

**Comment by maarcingebala** [comment]
Looks like the [comment above](https://github.com/saleor/saleor/issues/7431#issuecomment-960915619) provides a solution, so I'm closing the ticket. Please reopen if that doesn't help.
