### ISSUE TITLE
Building Saleor API container fails on collectstatic.

### ISSUE THREAD

**Issue by vetostream** [saleor/saleor#7856]
### What I'm trying to achieve
Build saleor platform on local machine.

### Steps to reproduce the problem
```
 => ERROR [stage-1 9/9] RUN SECRET_KEY=dummy STATIC_URL=/static/ python3 manage.py collectstatic --no-input                                                                                          0.6s
------                                                                                                                                                                                                    
 > [stage-1 9/9] RUN SECRET_KEY=dummy STATIC_URL=/static/ python3 manage.py collectstatic --no-input:                                                                                                     
#19 0.577 Traceback (most recent call last):                                                                                                                                                              
#19 0.577   File "manage.py", line 10, in <module>                                                                                                                                                        
#19 0.577     execute_from_command_line(sys.argv)                                                                                                                                                         
#19 0.577   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line                                                                      
#19 0.577     utility.execute()
#19 0.577   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
#19 0.577     django.setup()
#19 0.577   File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
#19 0.577     apps.populate(settings.INSTALLED_APPS)
#19 0.577   File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
#19 0.577     app_config = AppConfig.create(entry)
#19 0.577   File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 116, in create
#19 0.577     mod = import_module(mod_path)
#19 0.577   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
#19 0.577     return _bootstrap._gcd_import(name[level:], package, level)
#19 0.577   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
#19 0.577   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
#19 0.577   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
#19 0.577   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
#19 0.577   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
#19 0.577   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
#19 0.577   File "/usr/local/lib/python3.8/site-packages/django/contrib/postgres/apps.py", line 1, in <module>
#19 0.577     from psycopg2.extras import (
#19 0.577   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 51, in <module>
#19 0.577     from psycopg2._psycopg import (                     # noqa
#19 0.577 ImportError: libpq.so.5: cannot open shared object file: No such file or directory
------
executor failed running [/bin/sh -c SECRET_KEY=dummy STATIC_URL=${STATIC_URL} python3 manage.py collectstatic --no-input]: exit code: 1
ERROR: Service 'api' failed to build : Build failed
```

### What I expected to happen
Should build saleor platform properly

**System information**

Saleor version:
- [ ] dev (current master)
- [ ] 3.0
- [x] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [x] MacOS (BigSur, M1)
- [ ] Other

**Comment by suparerkk** [comment]
same issue with Saleor 3.0

**Comment by Radek-Wawrzyk** [comment]
Same issue on the main branch (MacOS, BigSur, M1)

**Comment by masiama** [comment]
Updating `Dockerfile` in `saleor` solved this issue for me

```diff
...
  RUN apt-get update \
    && apt-get install -y \
    libxml2 \
    libssl1.1 \
    libcairo2 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libgdk-pixbuf2.0-0 \
    shared-mime-info \
    mime-support \
+   gettext \
+   libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
+ 
+ RUN pip install psycopg2-binary
...
```
