### ISSUE TITLE
Bug: `0001_migrate_metadata` fails when building from empty database

### ISSUE THREAD

**Issue by onecrayon** [saleor/saleor#8527]
### What I'm trying to achieve
I am trying to build a local Saleor instance locally, from an empty database.

### Steps to reproduce the problem
The migration `core.0001_migrate_metadata` fails with the following output:

```
File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 268, in get_model
    return self.models[model_name.lower()]
KeyError: 'attribute'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/app/saleor/core/migrations/0001_migrate_metadata.py", line 33, in flatten_attributes_metadata
    Attribute = apps.get_model("product", "Attribute")
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 211, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 270, in get_model
    raise LookupError(
LookupError: App 'product' doesn't have a 'Attribute' model.
```

Commenting out line 114 of the affected file "fixes" the problem.

**System information**

Saleor version:
- [ ] dev (current main)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

**Comment by karolkielecki** [comment]
@onecrayon Thanks for reporting. I've passed the issue to the team. We'll keep you updated.

**Comment by montenegrop** [comment]
@onecrayon Hey, did you try deleting that part of the migration? I have the same issue right now, also I'm not sure how the models connect the attributes of a product, did you study that?
