### ISSUE TITLE
PluginX has no attribute 'name'

### ISSUE THREAD

**Issue by LeOndaz** [saleor/saleor#8873]
Created a plugin, here's the webhook
```
    def webhook(self, request, path, previous_value):
        request.app = self
        view = GraphQLView.as_view(schema=schema)
        return view(request)
```
and I get
```
api_1    | ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:22:Thread-1]
api_1    | Traceback (most recent call last):
api_1    |   File "/usr/local/lib/python3.9/site-packages/promise/promise.py", line 489, in _resolve_from_executor
api_1    |     executor(resolve, reject)
api_1    |   File "/usr/local/lib/python3.9/site-packages/promise/promise.py", line 756, in executor
api_1    |     return resolve(f(*args, **kwargs))
api_1    |   File "/usr/local/lib/python3.9/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
api_1    |     return next(*args, **kwargs)
api_1    |   File "/app/saleor/graphql/core/mutations.py", line 339, in mutate
api_1    |     response = cls.perform_mutation(root, info, **data)
api_1    |   File "/app/saleor/plugins/otp/graphql/mutations.py", line 93, in perform_mutation
api_1    |     send_password_reset_notification(
api_1    |   File "/app/saleor/plugins/otp/graphql/mutations.py", line 51, in send_password_reset_notification
api_1    |     manager.notify(event, payload=payload, channel_slug=channel_slug)
api_1    |   File "/app/saleor/plugins/manager.py", line 1072, in notify
api_1    |     return self.__run_method_on_plugins(
api_1    |   File "/app/saleor/plugins/manager.py", line 138, in __run_method_on_plugins
api_1    |     value = self.__run_method_on_single_plugin(
api_1    |   File "/app/saleor/plugins/manager.py", line 160, in __run_method_on_single_plugin
api_1    |     returned_value = plugin_method(*args, **kwargs, previous_value=previous_value)
api_1    |   File "/app/saleor/plugins/webhook/plugin.py", line 357, in notify
api_1    |     "meta": generate_meta(requestor_data=generate_requestor(self.requestor)),
api_1    |   File "/app/saleor/webhook/payloads.py", line 103, in generate_requestor
api_1    |     return {"id": requestor.name, "type": "app"}  # type: ignore
api_1    |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 247, in inner
api_1    |     return func(self._wrapped, *args)
api_1    | AttributeError: 'OTPPlugin' object has no attribute 'name'
```
adding a name attribute solves the error, but this is just a workaround

Also, I've many plugins installed and many of them use the same webhook, not sure why it's happening only with this one, none of them have a name attribute

**Comment by maarcingebala** [comment]
Closing for now as this doesn't happen for any other plugin, let's reopen if it happens again.
