### ISSUE TITLE
Saleor should validate currencies for external shipping methods

### ISSUE THREAD

**Issue by stnatic** [saleor/saleor#9139]
### Steps to reproduce the problem
1. I have returned a currency code `pln` from the external shipping app. This could have been any other valid currency such as `EUR` or `USD`.
2. I selected that external shipping method
3. Fetching `totalPrice` field fails from now on, until the shipping methods is updated to the one in the same currency as the checkout

### What I expected to happen
I would expect Saleor to filter our shipping methods with a mismatched currency.

### Screenshots and logs
```
Traceback (most recent call last):
  File "/Users/PycharmProjects/saleor/venv/lib/python3.9/site-packages/promise/promise.py", line 87, in try_catch
    return (handler(*args, **kwargs), None)
  File "/Users/PycharmProjects/saleor/saleor/graphql/checkout/types.py", line 396, in calculate_total_price
    calculations.checkout_total(
  File "/Users/PycharmProjects/saleor/saleor/checkout/calculations.py", line 88, in checkout_total
    calculated_checkout_total = manager.calculate_checkout_total(
  File "/Users/PycharmProjects/saleor/saleor/plugins/manager.py", line 205, in calculate_checkout_total
    default_value = base_calculations.base_checkout_total(
  File "/Users/PycharmProjects/saleor/saleor/checkout/base_calculations.py", line 189, in base_checkout_total
    total = subtotal + shipping_price - discount
  File "/Users/PycharmProjects/saleor/venv/lib/python3.9/site-packages/prices/taxed_money.py", line 73, in __add__
    net = self.net + other.net
  File "/Users/PycharmProjects/saleor/venv/lib/python3.9/site-packages/prices/money.py", line 84, in __add__
    raise ValueError(
ValueError: Cannot add amount in 'PLN' to 'pln'
```

**System information**

Saleor version:
- [x] dev (current main)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

**Comment by aniav** [comment]
This has been resolved in https://github.com/saleor/saleor/pull/16015 and ported to versions 3.14+
