### ISSUE TITLE
`productVariantBulkCreate` fails since 3.3.0

### ISSUE THREAD

**Issue by rrrnld** [saleor/saleor#9676]
### What I'm trying to achieve

I have a product that I want to publish by creating multiple product variants at once. I call `productCreate` first, and then publish it by calling variants in different channels. This fails since updating to 3.3.0, possibly because the product variants are lacking the fields expected for building the search vector:

```
{
      "stack": "Error: reduce() of empty sequence with no initial value: {\"response\":{\"errors\":[{\"message\":\"reduce() of empty sequence with no initial value\",\"locations\":[{\"line\":2,\"column\":3}],\"path\":[\"productVariantBulkCreate\"],\"extensions\":{\"exception\":{\"code\":\"TypeError\",\"stacktrace\":[\"Traceback (most recent call last):\",\"  File \\\"/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py\\\", line 452, in resolve_or_error\",\"    return executor.execute(resolve_fn, source, info, **args)\",\"  File \\\"/usr/local/lib/python3.9/site-packages/graphql/execution/executors/sync.py\\\", line 16, in execute\",\"    return fn(*args, **kwargs)\",\"  File \\\"/app/saleor/graphql/core/mutations.py\\\", line 374, in mutate\",\"    response = cls.perform_mutation(root, info, **data)\",\"  File \\\"/usr/local/lib/python3.9/contextlib.py\\\", line 79, in inner\",\"    return func(*args, **kwds)\",\"  File \\\"/app/saleor/graphql/product/bulk_mutations/products.py\\\", line 559, in perform_mutation\",\"    update_product_search_vector(product)\",\"  File \\\"/app/saleor/product/search.py\\\", line 39, in update_product_search_vector\",\"    product.search_vector = prepare_product_search_vector_value(product)\",\"  File \\\"/app/saleor/product/search.py\\\", line 56, in prepare_product_search_vector_value\",\"    variants_vector = generate_variants_search_vector_value(product)\",\"  File \\\"/app/saleor/product/search.py\\\", line 69, in generate_variants_search_vector_value\",\"    search_vector = reduce(\",\"TypeError: reduce() of empty sequence with no initial value\"]}}}],\"data\":{\"productVariantBulkCreate\":null},\"extensions\":{\"cost\":{\"requestedQueryCost\":0,\"maximumAvailable\":50000}},\"status\":200,\"headers\":{}},\"request\":{\"query\":\"mutation ProductVariantBulkCreate($id: ID!, $inputs: [ProductVariantBulkCreateInput!]!) {\\n  productVariantBulkCreate(product: $id, variants: $inputs) {\\n    errors {\\n      ...BulkProductError\\n    }\\n  }\\n}\\n\\nfragment BulkProductError on BulkProductError {\\n  field\\n  code\\n  index\\n  channels\\n  message\\n}\\n\",\"variables\":{\"id\":\"UHJvZHVjdDoxMDA3\",\"inputs\":[{\"attributes\":[],\"channelListings\":[{\"channelId\":\"Q2hhbm5lbDoz\",\"price\":\"32.00\"},{\"channelId\":\"Q2hhbm5lbDox\",\"price\":\"44.00\"}]}]}}}\n    at /home/arne/dev/ems/bots/common/temp/node_modules/.pnpm/graphql-request@4.2.0_graphql@15.8.0/node_modules/graphql-request/dist/index.js:356:31\n    at step (/home/arne/dev/ems/bots/common/temp/node_modules/.pnpm/graphql-request@4.2.0_graphql@15.8.0/node_modules/graphql-request/dist/index.js:63:23)\n    at Object.next (/home/arne/dev/ems/bots/common/temp/node_modules/.pnpm/graphql-request@4.2.0_graphql@15.8.0/node_modules/graphql-request/dist/index.js:44:53)\n    at fulfilled (/home/arne/dev/ems/bots/common/temp/node_modules/.pnpm/graphql-request@4.2.0_graphql@15.8.0/node_modules/graphql-request/dist/index.js:35:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
      "message": "reduce() of empty sequence with no initial value: {\"response\":{\"errors\":[{\"message\":\"reduce() of empty sequence with no initial value\",\"locations\":[{\"line\":2,\"column\":3}],\"path\":[\"productVariantBulkCreate\"],\"extensions\":{\"exception\":{\"code\":\"TypeError\",\"stacktrace\":[\"Traceback (most recent call last):\",\"  File \\\"/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py\\\", line 452, in resolve_or_error\",\"    return executor.execute(resolve_fn, source, info, **args)\",\"  File \\\"/usr/local/lib/python3.9/site-packages/graphql/execution/executors/sync.py\\\", line 16, in execute\",\"    return fn(*args, **kwargs)\",\"  File \\\"/app/saleor/graphql/core/mutations.py\\\", line 374, in mutate\",\"    response = cls.perform_mutation(root, info, **data)\",\"  File \\\"/usr/local/lib/python3.9/contextlib.py\\\", line 79, in inner\",\"    return func(*args, **kwds)\",\"  File \\\"/app/saleor/graphql/product/bulk_mutations/products.py\\\", line 559, in perform_mutation\",\"    update_product_search_vector(product)\",\"  File \\\"/app/saleor/product/search.py\\\", line 39, in update_product_search_vector\",\"    product.search_vector = prepare_product_search_vector_value(product)\",\"  File \\\"/app/saleor/product/search.py\\\", line 56, in prepare_product_search_vector_value\",\"    variants_vector = generate_variants_search_vector_value(product)\",\"  File \\\"/app/saleor/product/search.py\\\", line 69, in generate_variants_search_vector_value\",\"    search_vector = reduce(\",\"TypeError: reduce() of empty sequence with no initial value\"]}}}],\"data\":{\"productVariantBulkCreate\":null},\"extensions\":{\"cost\":{\"requestedQueryCost\":0,\"maximumAvailable\":50000}},\"status\":200,\"headers\":{}},\"request\":{\"query\":\"mutation ProductVariantBulkCreate($id: ID!, $inputs: [ProductVariantBulkCreateInput!]!) {\\n  productVariantBulkCreate(product: $id, variants: $inputs) {\\n    errors {\\n      ...BulkProductError\\n    }\\n  }\\n}\\n\\nfragment BulkProductError on BulkProductError {\\n  field\\n  code\\n  index\\n  channels\\n  message\\n}\\n\",\"variables\":{\"id\":\"UHJvZHVjdDoxMDA3\",\"inputs\":[{\"attributes\":[],\"channelListings\":[{\"channelId\":\"Q2hhbm5lbDoz\",\"price\":\"32.00\"},{\"channelId\":\"Q2hhbm5lbDox\",\"price\":\"44.00\"}]}]}}}",
      "request": {
        "query": "mutation ProductVariantBulkCreate($id: ID!, $inputs: [ProductVariantBulkCreateInput!]!) {\n  productVariantBulkCreate(product: $id, variants: $inputs) {\n    errors {\n      ...BulkProductError\n    }\n  }\n}\n\nfragment BulkProductError on BulkProductError {\n  field\n  code\n  index\n  channels\n  message\n}\n",
        "variables": {
          "id": "UHJvZHVjdDoxMDA3",
          "inputs": [
            {
              "attributes": [],
              "channelListings": [
                {
                  "price": "32.00",
                  "channelId": "Q2hhbm5lbDoz"
                },
                {
                  "price": "44.00",
                  "channelId": "Q2hhbm5lbDox"
                }
              ]
            }
          ]
        }
      },
      "response": {
        "data": {
          "productVariantBulkCreate": null
        },
        "errors": [
          {
            "path": [
              "productVariantBulkCreate"
            ],
            "message": "reduce() of empty sequence with no initial value",
            "locations": [
              {
                "line": 2,
                "column": 3
              }
            ],
            "extensions": {
              "exception": {
                "code": "TypeError",
                "stacktrace": [
                  "Traceback (most recent call last):",
                  "  File \"/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py\", line 452, in resolve_or_error",
                  "    return executor.execute(resolve_fn, source, info, **args)",
                  "  File \"/usr/local/lib/python3.9/site-packages/graphql/execution/executors/sync.py\", line 16, in execute",
                  "    return fn(*args, **kwargs)",
                  "  File \"/app/saleor/graphql/core/mutations.py\", line 374, in mutate",
                  "    response = cls.perform_mutation(root, info, **data)",
                  "  File \"/usr/local/lib/python3.9/contextlib.py\", line 79, in inner",
                  "    return func(*args, **kwds)",
                  "  File \"/app/saleor/graphql/product/bulk_mutations/products.py\", line 559, in perform_mutation",
                  "    update_product_search_vector(product)",
                  "  File \"/app/saleor/product/search.py\", line 39, in update_product_search_vector",
                  "    product.search_vector = prepare_product_search_vector_value(product)",
                  "  File \"/app/saleor/product/search.py\", line 56, in prepare_product_search_vector_value",
                  "    variants_vector = generate_variants_search_vector_value(product)",
                  "  File \"/app/saleor/product/search.py\", line 69, in generate_variants_search_vector_value",
                  "    search_vector = reduce(",
                  "TypeError: reduce() of empty sequence with no initial value"
                ]
              }
            }
          }
        ],
        "status": 200,
        "headers": {},
        "extensions": {
          "cost": {
            "maximumAvailable": 50000,
            "requestedQueryCost": 0
          }
        }
      }
    }
```

**System information**

Saleor version:
- 3.3.0

Operating system:
- Linux

**Comment by heyarne** [comment]
It might be helpful to know that in my specific case I was able to work around this error like so:

1. Create the product using `productCreate`
2. Create _a single_ productvariant using `productVariantCreate`
3. Create the channel listing for the product
4. Create the channel listing for the product variant

**Comment by aniav** [comment]
This isse has been fixed in the newest version of Saleor 🙌
