### ISSUE TITLE
Unable to createsuperuser on current production-ready tag

### ISSUE THREAD

**Issue by ex5** [saleor/saleor#9745]
### What I'm trying to achieve

I'm trying to deploy (and run locally) a production-ready `saleor` using the `3.0` tag, as per the README.

### Steps to reproduce the problem

```
git clone https://github.com/saleor/saleor.git
cd saleor
git checkout 3.0
# create and activate a venv, run migrations
./manage.py createsuperuser
```
Last command fails with a traceback.

### What I expected to happen
A Django superuser is created successfully.

### Screenshots and logs
Traceback from `createsuperuser`:
```
Traceback (most recent call last):
  File "redacted/saleor-platform/saleor/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 189, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "redacted/saleor-platform/saleor/saleor/account/models.py", line 136, in create_superuser
    return self.create_user(
  File "redacted/saleor-platform/saleor/saleor/account/models.py", line 132, in create_user
    user.save()
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "redacted/.envs/saleor/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "search_document" of relation "account_user" violates not-null constraint
DETAIL:  Failing row contains (2, t, admin@example.com, t, t, redacted..., 2022-05-11 13:24:14.901151+00, null, null, null, null, , , , {}, {}, 00shtkdnxnOr, en, null, null).


```

**System information**

Saleor version:
- [ ] dev (current main)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by patrys** [comment]
The current stable branch is `3.3` and `createsuperuser` works as expected.
