### ISSUE TITLE
Successfully `python manage.py populatedb`

### ISSUE THREAD

**Issue by jiapei100** [saleor/saleor#9931]
### What I'm trying to achieve
Successfully `python manage.py populatedb`

### Steps to reproduce the problem

1. `python manage.py migrate` successfully first
2. `python manage.py populatedb`

### What I expected to happen
Successfully `python manage.py populatedb`

### Screenshots and logs
```console
➜  saleor git:(main) ✗ python manage.py populatedb
....../saleor/saleor/settings.py:176: UserWarning: SECRET_KEY not configured, using a random temporary key.
  warnings.warn("SECRET_KEY not configured, using a random temporary key.")
WARNING saleor.core.jwt_manager RSA_PRIVATE_KEY is missing. Using temporary key for local development with DEBUG mode. [PID:1715100:MainThread]
Channel: default-channel
Channel: channel-pln
Shipping Zone: Europe
Shipping Zone: Oceania
Shipping Zone: Asia
Shipping Zone: Americas
Shipping Zone: Africa
Created warehouses
Page type default-page created
Page about created
WARNING kombu.connection No hostname was supplied. Reverting to default 'localhost' [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[629e7a44-770c-4179-841b-549985486157] succeeded in 0.01231816799918306s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[bb232517-3f27-4661-9a62-c836b01be56b] succeeded in 0.0004808670000784332s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[9fc6ee30-fd58-42f0-ac5d-9c832aa14745] succeeded in 0.00046368699986487627s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[a4a41c10-b90e-4d3a-a651-95dd7d057e37] succeeded in 0.0004562369995255722s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[13c36c88-d103-4f70-87c1-778f809d9fc8] succeeded in 0.0004019779989903327s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[96e116d4-19e2-45aa-94e0-27888650f21f] succeeded in 0.000397447000068496s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[d43e4372-99ea-4564-8fd1-eaf6947cbffd] succeeded in 0.00047958600043784827s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[04e5c315-c517-4f13-aa2a-469b413ad63d] succeeded in 0.0004000469998572953s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[823fa88a-986a-4349-9d85-ea235456b9cf] succeeded in 0.0003993379996245494s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[f38e6e4b-f238-4d42-96eb-1e12b79e8275] succeeded in 0.00039798699981474783s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[2bf058c6-bcbe-4654-821f-9cf6fe935b2a] succeeded in 0.000392107000152464s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[5d9ace39-a126-4802-8bf3-c5051d4f5b53] succeeded in 0.00039919700066093355s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[19e0099f-57c6-4e32-98ec-991379f1c8c9] succeeded in 0.0003975670006184373s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[5caeb2bd-d1fd-4291-ac98-eb9e03a1ece1] succeeded in 0.00039359699985652696s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[26302041-b6a8-4486-8788-3cc52633fd99] succeeded in 0.0003940470014640596s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_category_background_image_thumbnails[ae03e219-2e7c-4b8e-893c-064dd17fc36f] succeeded in 0.00039948700032255147s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_collection_background_image_thumbnails[3cd4476f-12b4-47af-97ef-969755d17a6a] succeeded in 0.00038597800084971823s: None [PID:1715100:MainThread]
INFO celery.app.trace Task saleor.product.thumbnails.create_collection_background_image_thumbnails[f10cd806-94a6-447c-a97e-440af4a66ca0] succeeded in 0.00034482799856050406s: None [PID:1715100:MainThread]
Created products
INFO celery.app.trace Task saleor.product.tasks.update_products_discounted_prices_of_discount_task[0a0f9d10-1d2a-4145-a6fc-9ba2949eed29] succeeded in 0.01573266400009743s: None [PID:1715100:MainThread]
Sale: Happy risk day!
INFO celery.app.trace Task saleor.product.tasks.update_products_discounted_prices_of_discount_task[8f6c9b05-c2d4-4178-9b79-c875e0e8b319] succeeded in 0.015921874000923708s: None [PID:1715100:MainThread]
Sale: Happy court day!
Shipping voucher already exists
Value voucher already exists
Value voucher already exists
User: craig.nash@example.com
User: erin.grant@example.com
User: kristine.higgins@example.com
User: kyle.vincent@example.com
User: holly.simmons@example.com
User: tracy.richards@example.com
User: karen.harris@example.com
User: erin.rich@example.com
User: megan.aguilar@example.com
User: arthur.davis@example.com
User: nicole.yang@example.com
User: brian.johnson@example.com
User: crystal.garcia@example.com
User: robert.garcia@example.com
User: michele.lopez@example.com
User: brittany.miller@example.com
User: david.evans@example.com
User: timothy.harris@example.com
User: thomas.gregory@example.com
User: randy.garcia@example.com
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/django/db/models/base.py", line 469, in __init__
    val = kwargs.pop(field.attname)
KeyError: 'number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedTable: relation "order_order_number_seq" does not exist
LINE 1: SELECT nextval('order_order_number_seq')
                       ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "....../saleor/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "~/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "~/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "~/.local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "~/.local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "....../saleor/saleor/core/management/commands/populatedb.py", line 107, in handle
    for msg in create_orders(20):
  File "....../saleor/saleor/core/utils/random_data.py", line 968, in create_orders
    order = create_fake_order(discounts)
  File "....../saleor/saleor/core/utils/random_data.py", line 827, in create_fake_order
    order = Order.objects.create(**order_data)
  File "~/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "~/.local/lib/python3.10/site-packages/django/db/models/query.py", line 451, in create
    obj = self.model(**kwargs)
  File "~/.local/lib/python3.10/site-packages/django/db/models/base.py", line 475, in __init__
    val = field.get_default()
  File "~/.local/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 850, in get_default
    return self._get_default()
  File "....../saleor/saleor/order/models.py", line 94, in get_order_number
    cursor.execute("SELECT nextval('order_order_number_seq')")
  File "~/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "~/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "~/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "~/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "~/.local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "~/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "order_order_number_seq" does not exist
LINE 1: SELECT nextval('order_order_number_seq')
                       ^
```

**System information**

Saleor version:
- [X] dev (current main)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by PlusA2M** [comment]
Hi @jiapei100 ! According to the output provided, I think you need to clear your db first before you do another `populatedb`, it seems you have some data already in the database.

**Comment by RajithJarang** [comment]
You might have missed this migration file 
https://github.com/cybernate-retail/core/blob/26ac2b89dccef7701d98229419c5ea495eac2cbe/saleor/order/migrations/0129_alter_order_number.py

add it migrate and it resolve that issue
